/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AuditCoverageData
 */
export interface AuditCoverageData {
    /**
     * ECC 数
     * @type {number}
     * @memberof AuditCoverageData
     */
    'ecc_count'?: number;
    /**
     * 分母（结案疗程数）
     * @type {number}
     * @memberof AuditCoverageData
     */
    'denominator_closed_courses'?: number;
    /**
     * 可判定覆盖率
     * @type {number}
     * @memberof AuditCoverageData
     */
    'decidable_coverage_rate'?: number;
    /**
     * 预留，本版不返回值（TBD）；上限 = s
     * @type {string}
     * @memberof AuditCoverageData
     */
    'a3_observability'?: string;
}

