/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BandTelemetryData
 */
export interface BandTelemetryData {
    /**
     * 未接入时数值字段不下发，不得显示 0 / 空图表 / 示例数据
     * @type {string}
     * @memberof BandTelemetryData
     */
    'data_source'?: BandTelemetryDataDataSourceEnum;
    /**
     * 已采集天数（正向计数）
     * @type {number}
     * @memberof BandTelemetryData
     */
    'collected_days'?: number;
    /**
     * 客户可见同步时间精确到日（不得到分秒）
     * @type {string}
     * @memberof BandTelemetryData
     */
    'synced_date'?: string;
    /**
     * 
     * @type {Array<object>}
     * @memberof BandTelemetryData
     */
    'metrics'?: Array<object>;
    /**
     * 🔴 客户恒 403 / 不下发（硬约束，配置不得放开）
     * @type {string}
     * @memberof BandTelemetryData
     */
    'gap_reason'?: BandTelemetryDataGapReasonEnum;
}

export const BandTelemetryDataDataSourceEnum = {
    : '手环',
    2: '未接入'
} as const;

export type BandTelemetryDataDataSourceEnum = typeof BandTelemetryDataDataSourceEnum[keyof typeof BandTelemetryDataDataSourceEnum];
export const BandTelemetryDataGapReasonEnum = {
    NoOpen: 'no_open',
    SyncFailed: 'sync_failed',
    NotWorn: 'not_worn',
    CompliantRemoval: 'compliant_removal',
    InvoluntaryTechnical: 'involuntary_technical',
    BeyondRetentionWindow: 'beyond_retention_window',
    Unknown: 'unknown'
} as const;

export type BandTelemetryDataGapReasonEnum = typeof BandTelemetryDataGapReasonEnum[keyof typeof BandTelemetryDataGapReasonEnum];


