/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateCycleAssessmentRequestAdherence } from './create-cycle-assessment-request-adherence';

/**
 * 
 * @export
 * @interface CreateCycleAssessmentRequest
 */
export interface CreateCycleAssessmentRequest {
    /**
     * 周期评估主键（必填 —— 使 F1 能在同一行上补判定）
     * @type {string}
     * @memberof CreateCycleAssessmentRequest
     */
    'cycle_id': string;
    /**
     * 第 N 次评估（每 7 次触发）
     * @type {number}
     * @memberof CreateCycleAssessmentRequest
     */
    'sequence_no': number;
    /**
     * 
     * @type {CreateCycleAssessmentRequestAdherence}
     * @memberof CreateCycleAssessmentRequest
     */
    'adherence': CreateCycleAssessmentRequestAdherence;
    /**
     * 应填天数（样本护栏）
     * @type {number}
     * @memberof CreateCycleAssessmentRequest
     */
    'expected_days'?: number;
    /**
     * 模块分 M1–M5（各 0–16）
     * @type {{ [key: string]: number; }}
     * @memberof CreateCycleAssessmentRequest
     */
    'module_scores': { [key: string]: number; };
    /**
     * 
     * @type {string}
     * @memberof CreateCycleAssessmentRequest
     */
    'band_trend_note'?: string;
    /**
     * 断言位（可空 = 服务端填；非空须逐字等于服务端指纹）
     * @type {string}
     * @memberof CreateCycleAssessmentRequest
     */
    'threshold_version'?: string;
}

