/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateVerdictRequestAdherence } from './create-verdict-request-adherence';
// May contain unused imports in some cases
// @ts-ignore
import type { CreateVerdictRequestConfidence } from './create-verdict-request-confidence';
// May contain unused imports in some cases
// @ts-ignore
import type { CreateVerdictRequestSameOrigin } from './create-verdict-request-same-origin';

/**
 * 
 * @export
 * @interface CreateVerdictRequest
 */
export interface CreateVerdictRequest {
    /**
     * 客户（用于历史查询与越权判定）
     * @type {string}
     * @memberof CreateVerdictRequest
     */
    'customer_id': string;
    /**
     * 第 N 次评估
     * @type {number}
     * @memberof CreateVerdictRequest
     */
    'sequence_no': number;
    /**
     * 基线模块总分；缺失 ⇒ 挂起（D5）
     * @type {number}
     * @memberof CreateVerdictRequest
     */
    'base_total'?: number;
    /**
     * 复评模块总分；缺失 ⇒ 挂起（D5）
     * @type {number}
     * @memberof CreateVerdictRequest
     */
    'current_total'?: number;
    /**
     * 
     * @type {CreateVerdictRequestSameOrigin}
     * @memberof CreateVerdictRequest
     */
    'same_origin': CreateVerdictRequestSameOrigin;
    /**
     * 
     * @type {CreateVerdictRequestAdherence}
     * @memberof CreateVerdictRequest
     */
    'adherence': CreateVerdictRequestAdherence;
    /**
     * 🛑 缺失 ⇒ 未定（不得默认「无」—— 那会让 D4 该触发而不触发）
     * @type {string}
     * @memberof CreateVerdictRequest
     */
    'risk_flag': CreateVerdictRequestRiskFlagEnum;
    /**
     * 经络师结构化录入；缺失 ⇒ 挂起
     * @type {boolean}
     * @memberof CreateVerdictRequest
     */
    'core_metric_improved': boolean;
    /**
     * 
     * @type {CreateVerdictRequestConfidence}
     * @memberof CreateVerdictRequest
     */
    'confidence': CreateVerdictRequestConfidence;
    /**
     * 模块分 M1–M5（各 0–16）
     * @type {{ [key: string]: number; }}
     * @memberof CreateVerdictRequest
     */
    'module_scores': { [key: string]: number; };
    /**
     * 手环趋势说明（U-15 四条备注语义的载体）
     * @type {string}
     * @memberof CreateVerdictRequest
     */
    'band_trend_note'?: string;
    /**
     * 🛑【断言位，不是取值位】可空（空 = 服务端按当前口径填）； 非空时必须逐字等于服务端算出的内容寻址指纹，否则拒写 4001。 
     * @type {string}
     * @memberof CreateVerdictRequest
     */
    'threshold_version'?: string;
}

export const CreateVerdictRequestRiskFlagEnum = {
    : '无',
    2: '高危',
    3: '新发',
    4: '同病'
} as const;

export type CreateVerdictRequestRiskFlagEnum = typeof CreateVerdictRequestRiskFlagEnum[keyof typeof CreateVerdictRequestRiskFlagEnum];


