/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CustomerDetailData
 */
export interface CustomerDetailData {
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailData
     */
    'customer_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailData
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailData
     */
    'gender'?: string;
    /**
     * 
     * @type {number}
     * @memberof CustomerDetailData
     */
    'age'?: number;
    /**
     * 
     * @type {object}
     * @memberof CustomerDetailData
     */
    'intake_profile'?: object;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailData
     */
    'screening_result'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailData
     */
    'band_willingness'?: CustomerDetailDataBandWillingnessEnum;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailData
     */
    'owner_store_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CustomerDetailData
     */
    'serving_store_id'?: string;
    /**
     * 派生字段；客户 token 请求 include=verdict → 403 VISIBILITY_DENIED
     * @type {string}
     * @memberof CustomerDetailData
     */
    'effect_verdict'?: string;
    /**
     * 派生字段；客户恒不下发
     * @type {number}
     * @memberof CustomerDetailData
     */
    'as_value'?: number;
}

export const CustomerDetailDataBandWillingnessEnum = {
    : '自愿佩戴',
    2: '暂不佩戴'
} as const;

export type CustomerDetailDataBandWillingnessEnum = typeof CustomerDetailDataBandWillingnessEnum[keyof typeof CustomerDetailDataBandWillingnessEnum];


