/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface LoginData
 */
export interface LoginData {
    /**
     * 
     * @type {string}
     * @memberof LoginData
     */
    'token'?: string;
    /**
     * 
     * @type {number}
     * @memberof LoginData
     */
    'expires_in'?: number;
    /**
     * 客户=client / 调理师=therapist / 经络师=meridian / 门店负责人=manager / 区域督导=area / 总部运营=hq
     * @type {string}
     * @memberof LoginData
     */
    'role'?: LoginDataRoleEnum;
    /**
     * 
     * @type {string}
     * @memberof LoginData
     */
    'client_end'?: LoginDataClientEndEnum;
    /**
     * 
     * @type {string}
     * @memberof LoginData
     */
    'tenant_id'?: string;
    /**
     * 客户无 staff_id（差异项）
     * @type {string}
     * @memberof LoginData
     */
    'staff_id'?: string;
}

export const LoginDataRoleEnum = {
    Client: 'client',
    Therapist: 'therapist',
    Meridian: 'meridian',
    Manager: 'manager',
    Area: 'area',
    Hq: 'hq'
} as const;

export type LoginDataRoleEnum = typeof LoginDataRoleEnum[keyof typeof LoginDataRoleEnum];
export const LoginDataClientEndEnum = {
    Mp: 'mp',
    App: 'app',
    Web: 'web'
} as const;

export type LoginDataClientEndEnum = typeof LoginDataClientEndEnum[keyof typeof LoginDataClientEndEnum];


