/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RefundCreateRequest
 */
export interface RefundCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof RefundCreateRequest
     */
    'customer_id': string;
    /**
     * 
     * @type {string}
     * @memberof RefundCreateRequest
     */
    'entry': RefundCreateRequestEntryEnum;
    /**
     * 
     * @type {string}
     * @memberof RefundCreateRequest
     */
    'refund_route': RefundCreateRequestRefundRouteEnum;
    /**
     * 必填；未记录原因不可结案
     * @type {string}
     * @memberof RefundCreateRequest
     */
    'reason_code': RefundCreateRequestReasonCodeEnum;
    /**
     * 最早且可核实
     * @type {string}
     * @memberof RefundCreateRequest
     */
    'requested_at': string;
    /**
     * 客户主张，仅留存不计时
     * @type {string}
     * @memberof RefundCreateRequest
     */
    'requested_at_claimed'?: string;
    /**
     * append-only 原话
     * @type {string}
     * @memberof RefundCreateRequest
     */
    'customer_statement'?: string;
}

export const RefundCreateRequestEntryEnum = {
    A: 'A门店代录',
    B: 'B首周期'
} as const;

export type RefundCreateRequestEntryEnum = typeof RefundCreateRequestEntryEnum[keyof typeof RefundCreateRequestEntryEnum];
export const RefundCreateRequestRefundRouteEnum = {
    : '履约类',
    2: '效果类'
} as const;

export type RefundCreateRequestRefundRouteEnum = typeof RefundCreateRequestRefundRouteEnum[keyof typeof RefundCreateRequestRefundRouteEnum];
export const RefundCreateRequestReasonCodeEnum = {
    : '效果未达预期',
    2: '症状加重或出现新不适',
    3: '服务体验或沟通问题',
    4: '时间·经济·家庭原因',
    5: '配合度不足导致无明显变化',
    6: '信任或价格异议'
} as const;

export type RefundCreateRequestReasonCodeEnum = typeof RefundCreateRequestReasonCodeEnum[keyof typeof RefundCreateRequestReasonCodeEnum];


