/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface VerdictData
 */
export interface VerdictData {
    /**
     * 
     * @type {string}
     * @memberof VerdictData
     */
    'verdict_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerdictData
     */
    'branch'?: VerdictDataBranchEnum;
    /**
     * 
     * @type {number}
     * @memberof VerdictData
     */
    'confidence'?: number;
    /**
     * 
     * @type {object}
     * @memberof VerdictData
     */
    'evidence_snapshot'?: object;
    /**
     * 
     * @type {string}
     * @memberof VerdictData
     */
    'threshold_version'?: string;
    /**
     * 
     * @type {string}
     * @memberof VerdictData
     */
    'decided_at'?: string;
}

export const VerdictDataBranchEnum = {
    : '稳定',
    2: '依从不足',
    3: '达标无效',
    4: '全面评估',
    5: '人工复核'
} as const;

export type VerdictDataBranchEnum = typeof VerdictDataBranchEnum[keyof typeof VerdictDataBranchEnum];


