/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AgeGroup from './model/AgeGroup';
import AuthLogin200Response from './model/AuthLogin200Response';
import AuthLoginRequest from './model/AuthLoginRequest';
import AuthMe200Response from './model/AuthMe200Response';
import AuthMeData from './model/AuthMeData';
import AuthMeDataBandVisibility from './model/AuthMeDataBandVisibility';
import AuthMeDataStoreScope from './model/AuthMeDataStoreScope';
import BandAvailableDatesData from './model/BandAvailableDatesData';
import BandAvailableDatesDataRetentionWindowDays from './model/BandAvailableDatesDataRetentionWindowDays';
import BandAvailableDatesRequest from './model/BandAvailableDatesRequest';
import BandSyncBatchRequest from './model/BandSyncBatchRequest';
import BandSyncStatusData from './model/BandSyncStatusData';
import BandTelemetryData from './model/BandTelemetryData';
import BandTelemetryRequest from './model/BandTelemetryRequest';
import CustomerDetailData from './model/CustomerDetailData';
import DailyReportData from './model/DailyReportData';
import DailyReportRequest from './model/DailyReportRequest';
import Dimension from './model/Dimension';
import GetBandSyncStatus200Response from './model/GetBandSyncStatus200Response';
import GetBandTelemetry200Response from './model/GetBandTelemetry200Response';
import GetCustomer200Response from './model/GetCustomer200Response';
import LoginData from './model/LoginData';
import ReportBandAvailableDates200Response from './model/ReportBandAvailableDates200Response';
import ResultEnvelope from './model/ResultEnvelope';
import SubmitDailyReport200Response from './model/SubmitDailyReport200Response';
import AApi from './api/AApi';
import BApi from './api/BApi';
import CApi from './api/CApi';
import DApi from './api/DApi';
import EApi from './api/EApi';


/**
* 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\&quot;体验优化\&quot;处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end&#x3D;mp 可见字段不得含\&quot;退款\&quot;\&quot;诊断\&quot;；同步时间精确到日。 .<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var DyClientSdk = require('index'); // See note below*.
* var xxxSvc = new DyClientSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new DyClientSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new DyClientSdk.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new DyClientSdk.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version api-contract-v1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AgeGroup model constructor.
     * @property {module:model/AgeGroup}
     */
    AgeGroup,

    /**
     * The AuthLogin200Response model constructor.
     * @property {module:model/AuthLogin200Response}
     */
    AuthLogin200Response,

    /**
     * The AuthLoginRequest model constructor.
     * @property {module:model/AuthLoginRequest}
     */
    AuthLoginRequest,

    /**
     * The AuthMe200Response model constructor.
     * @property {module:model/AuthMe200Response}
     */
    AuthMe200Response,

    /**
     * The AuthMeData model constructor.
     * @property {module:model/AuthMeData}
     */
    AuthMeData,

    /**
     * The AuthMeDataBandVisibility model constructor.
     * @property {module:model/AuthMeDataBandVisibility}
     */
    AuthMeDataBandVisibility,

    /**
     * The AuthMeDataStoreScope model constructor.
     * @property {module:model/AuthMeDataStoreScope}
     */
    AuthMeDataStoreScope,

    /**
     * The BandAvailableDatesData model constructor.
     * @property {module:model/BandAvailableDatesData}
     */
    BandAvailableDatesData,

    /**
     * The BandAvailableDatesDataRetentionWindowDays model constructor.
     * @property {module:model/BandAvailableDatesDataRetentionWindowDays}
     */
    BandAvailableDatesDataRetentionWindowDays,

    /**
     * The BandAvailableDatesRequest model constructor.
     * @property {module:model/BandAvailableDatesRequest}
     */
    BandAvailableDatesRequest,

    /**
     * The BandSyncBatchRequest model constructor.
     * @property {module:model/BandSyncBatchRequest}
     */
    BandSyncBatchRequest,

    /**
     * The BandSyncStatusData model constructor.
     * @property {module:model/BandSyncStatusData}
     */
    BandSyncStatusData,

    /**
     * The BandTelemetryData model constructor.
     * @property {module:model/BandTelemetryData}
     */
    BandTelemetryData,

    /**
     * The BandTelemetryRequest model constructor.
     * @property {module:model/BandTelemetryRequest}
     */
    BandTelemetryRequest,

    /**
     * The CustomerDetailData model constructor.
     * @property {module:model/CustomerDetailData}
     */
    CustomerDetailData,

    /**
     * The DailyReportData model constructor.
     * @property {module:model/DailyReportData}
     */
    DailyReportData,

    /**
     * The DailyReportRequest model constructor.
     * @property {module:model/DailyReportRequest}
     */
    DailyReportRequest,

    /**
     * The Dimension model constructor.
     * @property {module:model/Dimension}
     */
    Dimension,

    /**
     * The GetBandSyncStatus200Response model constructor.
     * @property {module:model/GetBandSyncStatus200Response}
     */
    GetBandSyncStatus200Response,

    /**
     * The GetBandTelemetry200Response model constructor.
     * @property {module:model/GetBandTelemetry200Response}
     */
    GetBandTelemetry200Response,

    /**
     * The GetCustomer200Response model constructor.
     * @property {module:model/GetCustomer200Response}
     */
    GetCustomer200Response,

    /**
     * The LoginData model constructor.
     * @property {module:model/LoginData}
     */
    LoginData,

    /**
     * The ReportBandAvailableDates200Response model constructor.
     * @property {module:model/ReportBandAvailableDates200Response}
     */
    ReportBandAvailableDates200Response,

    /**
     * The ResultEnvelope model constructor.
     * @property {module:model/ResultEnvelope}
     */
    ResultEnvelope,

    /**
     * The SubmitDailyReport200Response model constructor.
     * @property {module:model/SubmitDailyReport200Response}
     */
    SubmitDailyReport200Response,

    /**
    * The AApi service constructor.
    * @property {module:api/AApi}
    */
    AApi,

    /**
    * The BApi service constructor.
    * @property {module:api/BApi}
    */
    BApi,

    /**
    * The CApi service constructor.
    * @property {module:api/CApi}
    */
    CApi,

    /**
    * The DApi service constructor.
    * @property {module:api/DApi}
    */
    DApi,

    /**
    * The EApi service constructor.
    * @property {module:api/EApi}
    */
    EApi
};
