/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AuthLogin200Response } from '../model';
// @ts-ignore
import type { AuthLoginRequest } from '../model';
// @ts-ignore
import type { AuthMe200Response } from '../model';
// @ts-ignore
import type { ListStores200Response } from '../model';
// @ts-ignore
import type { ResultEnvelope } from '../model';
/**
 * AApi - axios parameter creator
 * @export
 */
export const AApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary A1 登录，签发 token
         * @param {AuthLoginRequest} authLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogin: async (authLoginRequest: AuthLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authLoginRequest' is not null or undefined
            assertParamExists('authLogin', 'authLoginRequest', authLoginRequest)
            const localVarPath = `/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authLoginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ⚠️ 本接口只下发「档位布尔值」，不下发任何业务字段 —— 它是声明，不是数据。 三端 UI 依此声明决定渲染分支，但字段仍由服务端裁剪（X-1：声明 ≠ 授权，二者须一致）。 
         * @summary A2 当前身份 + 角色 + 可见性档位解算结果（可见性档位唯一权威下发点）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authMe: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/auth/me`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary A3 门店列表（按行级 scope 过滤）
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listStores: async (page?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/stores`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AApi - functional programming interface
 * @export
 */
export const AApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary A1 登录，签发 token
         * @param {AuthLoginRequest} authLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authLogin(authLoginRequest: AuthLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthLogin200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authLogin(authLoginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AApi.authLogin']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * ⚠️ 本接口只下发「档位布尔值」，不下发任何业务字段 —— 它是声明，不是数据。 三端 UI 依此声明决定渲染分支，但字段仍由服务端裁剪（X-1：声明 ≠ 授权，二者须一致）。 
         * @summary A2 当前身份 + 角色 + 可见性档位解算结果（可见性档位唯一权威下发点）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async authMe(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuthMe200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.authMe(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AApi.authMe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary A3 门店列表（按行级 scope 过滤）
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listStores(page?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ListStores200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listStores(page, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AApi.listStores']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AApi - factory interface
 * @export
 */
export const AApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AApiFp(configuration)
    return {
        /**
         * 
         * @summary A1 登录，签发 token
         * @param {AuthLoginRequest} authLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authLogin(authLoginRequest: AuthLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuthLogin200Response> {
            return localVarFp.authLogin(authLoginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * ⚠️ 本接口只下发「档位布尔值」，不下发任何业务字段 —— 它是声明，不是数据。 三端 UI 依此声明决定渲染分支，但字段仍由服务端裁剪（X-1：声明 ≠ 授权，二者须一致）。 
         * @summary A2 当前身份 + 角色 + 可见性档位解算结果（可见性档位唯一权威下发点）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        authMe(options?: RawAxiosRequestConfig): AxiosPromise<AuthMe200Response> {
            return localVarFp.authMe(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary A3 门店列表（按行级 scope 过滤）
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listStores(page?: number, pageSize?: number, options?: RawAxiosRequestConfig): AxiosPromise<ListStores200Response> {
            return localVarFp.listStores(page, pageSize, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AApi - object-oriented interface
 * @export
 * @class AApi
 * @extends {BaseAPI}
 */
export class AApi extends BaseAPI {
    /**
     * 
     * @summary A1 登录，签发 token
     * @param {AuthLoginRequest} authLoginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AApi
     */
    public authLogin(authLoginRequest: AuthLoginRequest, options?: RawAxiosRequestConfig) {
        return AApiFp(this.configuration).authLogin(authLoginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ⚠️ 本接口只下发「档位布尔值」，不下发任何业务字段 —— 它是声明，不是数据。 三端 UI 依此声明决定渲染分支，但字段仍由服务端裁剪（X-1：声明 ≠ 授权，二者须一致）。 
     * @summary A2 当前身份 + 角色 + 可见性档位解算结果（可见性档位唯一权威下发点）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AApi
     */
    public authMe(options?: RawAxiosRequestConfig) {
        return AApiFp(this.configuration).authMe(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary A3 门店列表（按行级 scope 过滤）
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AApi
     */
    public listStores(page?: number, pageSize?: number, options?: RawAxiosRequestConfig) {
        return AApiFp(this.configuration).listStores(page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }
}

