/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateCustomer200Response } from '../model';
// @ts-ignore
import type { CreateScreeningRecord200Response } from '../model';
// @ts-ignore
import type { CustomerCreateRequest } from '../model';
// @ts-ignore
import type { GetCustomer200Response } from '../model';
// @ts-ignore
import type { ResultEnvelope } from '../model';
// @ts-ignore
import type { ScreeningCreateRequest } from '../model';
/**
 * BApi - axios parameter creator
 * @export
 */
export const BApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 需 screening_result=通过。phone 为租户内唯一（跨店识别键）。
         * @summary B2 建档（POST /archive 语义）
         * @param {CustomerCreateRequest} customerCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCustomer: async (customerCreateRequest: CustomerCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'customerCreateRequest' is not null or undefined
            assertParamExists('createCustomer', 'customerCreateRequest', customerCreateRequest)
            const localVarPath = `/customers`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(customerCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 命中禁忌（result=不通过）→ 客户状态置 REJECTED，后续 B2/B3 入口 403 GATE_MISSING （missing_items=[\"screening_result\"]）。记录不可删除。 
         * @summary B1 禁忌筛查提交（硬门禁①）
         * @param {ScreeningCreateRequest} screeningCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createScreeningRecord: async (screeningCreateRequest: ScreeningCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'screeningCreateRequest' is not null or undefined
            assertParamExists('createScreeningRecord', 'screeningCreateRequest', screeningCreateRequest)
            const localVarPath = `/screening-records`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(screeningCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 🔴 客户 token 请求含派生字段的 query（如 ?include=verdict）→ 403 VISIBILITY_DENIED， data.denied_fields 回显被拒字段名。 
         * @summary B4 客户详情（可见性裁剪重点接口）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {string} [include] 追加字段（如 verdict）；命中客户不可见字段组时 403 VISIBILITY_DENIED
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomer: async (id: string, include?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getCustomer', 'id', id)
            const localVarPath = `/customers/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (include !== undefined) {
                localVarQueryParameter['include'] = include;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary B5 建档扩展档案
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIntakeProfile: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getIntakeProfile', 'id', id)
            const localVarPath = `/customers/{id}/intake-profile`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary B6 补充 + 修订（append-only 留痕，不可覆盖）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchIntakeProfile: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('patchIntakeProfile', 'id', id)
            const localVarPath = `/customers/{id}/intake-profile`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 需 PROFILED（门禁 G1：未建档不得签知情同意书）。
         * @summary B3 签知情同意书
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signConsent: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('signConsent', 'id', id)
            const localVarPath = `/customers/{id}/consents`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BApi - functional programming interface
 * @export
 */
export const BApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BApiAxiosParamCreator(configuration)
    return {
        /**
         * 需 screening_result=通过。phone 为租户内唯一（跨店识别键）。
         * @summary B2 建档（POST /archive 语义）
         * @param {CustomerCreateRequest} customerCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createCustomer(customerCreateRequest: CustomerCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateCustomer200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createCustomer(customerCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BApi.createCustomer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 命中禁忌（result=不通过）→ 客户状态置 REJECTED，后续 B2/B3 入口 403 GATE_MISSING （missing_items=[\"screening_result\"]）。记录不可删除。 
         * @summary B1 禁忌筛查提交（硬门禁①）
         * @param {ScreeningCreateRequest} screeningCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createScreeningRecord(screeningCreateRequest: ScreeningCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateScreeningRecord200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createScreeningRecord(screeningCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BApi.createScreeningRecord']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 🔴 客户 token 请求含派生字段的 query（如 ?include=verdict）→ 403 VISIBILITY_DENIED， data.denied_fields 回显被拒字段名。 
         * @summary B4 客户详情（可见性裁剪重点接口）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {string} [include] 追加字段（如 verdict）；命中客户不可见字段组时 403 VISIBILITY_DENIED
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCustomer(id: string, include?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetCustomer200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCustomer(id, include, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BApi.getCustomer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary B5 建档扩展档案
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIntakeProfile(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getIntakeProfile(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BApi.getIntakeProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary B6 补充 + 修订（append-only 留痕，不可覆盖）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchIntakeProfile(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchIntakeProfile(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BApi.patchIntakeProfile']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 需 PROFILED（门禁 G1：未建档不得签知情同意书）。
         * @summary B3 签知情同意书
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signConsent(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signConsent(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BApi.signConsent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BApi - factory interface
 * @export
 */
export const BApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BApiFp(configuration)
    return {
        /**
         * 需 screening_result=通过。phone 为租户内唯一（跨店识别键）。
         * @summary B2 建档（POST /archive 语义）
         * @param {CustomerCreateRequest} customerCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createCustomer(customerCreateRequest: CustomerCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateCustomer200Response> {
            return localVarFp.createCustomer(customerCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 命中禁忌（result=不通过）→ 客户状态置 REJECTED，后续 B2/B3 入口 403 GATE_MISSING （missing_items=[\"screening_result\"]）。记录不可删除。 
         * @summary B1 禁忌筛查提交（硬门禁①）
         * @param {ScreeningCreateRequest} screeningCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createScreeningRecord(screeningCreateRequest: ScreeningCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateScreeningRecord200Response> {
            return localVarFp.createScreeningRecord(screeningCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 🔴 客户 token 请求含派生字段的 query（如 ?include=verdict）→ 403 VISIBILITY_DENIED， data.denied_fields 回显被拒字段名。 
         * @summary B4 客户详情（可见性裁剪重点接口）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {string} [include] 追加字段（如 verdict）；命中客户不可见字段组时 403 VISIBILITY_DENIED
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCustomer(id: string, include?: string, options?: RawAxiosRequestConfig): AxiosPromise<GetCustomer200Response> {
            return localVarFp.getCustomer(id, include, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary B5 建档扩展档案
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIntakeProfile(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.getIntakeProfile(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary B6 补充 + 修订（append-only 留痕，不可覆盖）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchIntakeProfile(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.patchIntakeProfile(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 需 PROFILED（门禁 G1：未建档不得签知情同意书）。
         * @summary B3 签知情同意书
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signConsent(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.signConsent(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BApi - object-oriented interface
 * @export
 * @class BApi
 * @extends {BaseAPI}
 */
export class BApi extends BaseAPI {
    /**
     * 需 screening_result=通过。phone 为租户内唯一（跨店识别键）。
     * @summary B2 建档（POST /archive 语义）
     * @param {CustomerCreateRequest} customerCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BApi
     */
    public createCustomer(customerCreateRequest: CustomerCreateRequest, options?: RawAxiosRequestConfig) {
        return BApiFp(this.configuration).createCustomer(customerCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 命中禁忌（result=不通过）→ 客户状态置 REJECTED，后续 B2/B3 入口 403 GATE_MISSING （missing_items=[\"screening_result\"]）。记录不可删除。 
     * @summary B1 禁忌筛查提交（硬门禁①）
     * @param {ScreeningCreateRequest} screeningCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BApi
     */
    public createScreeningRecord(screeningCreateRequest: ScreeningCreateRequest, options?: RawAxiosRequestConfig) {
        return BApiFp(this.configuration).createScreeningRecord(screeningCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 🔴 客户 token 请求含派生字段的 query（如 ?include=verdict）→ 403 VISIBILITY_DENIED， data.denied_fields 回显被拒字段名。 
     * @summary B4 客户详情（可见性裁剪重点接口）
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {string} [include] 追加字段（如 verdict）；命中客户不可见字段组时 403 VISIBILITY_DENIED
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BApi
     */
    public getCustomer(id: string, include?: string, options?: RawAxiosRequestConfig) {
        return BApiFp(this.configuration).getCustomer(id, include, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary B5 建档扩展档案
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BApi
     */
    public getIntakeProfile(id: string, options?: RawAxiosRequestConfig) {
        return BApiFp(this.configuration).getIntakeProfile(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary B6 补充 + 修订（append-only 留痕，不可覆盖）
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BApi
     */
    public patchIntakeProfile(id: string, options?: RawAxiosRequestConfig) {
        return BApiFp(this.configuration).patchIntakeProfile(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 需 PROFILED（门禁 G1：未建档不得签知情同意书）。
     * @summary B3 签知情同意书
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BApi
     */
    public signConsent(id: string, options?: RawAxiosRequestConfig) {
        return BApiFp(this.configuration).signConsent(id, options).then((request) => request(this.axios, this.basePath));
    }
}

