/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AgeGroup } from '../model';
// @ts-ignore
import type { BaselineAssessmentRequest } from '../model';
// @ts-ignore
import type { CreateCycleAssessmentRequest } from '../model';
// @ts-ignore
import type { Dimension } from '../model';
// @ts-ignore
import type { ResultEnvelope } from '../model';
// @ts-ignore
import type { SubmitBaselineAssessment200Response } from '../model';
/**
 * CApi - axios parameter creator
 * @export
 */
export const CApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary C3 评估详情
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {string} assessmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAssessment: async (id: string, assessmentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getAssessment', 'id', id)
            // verify required parameter 'assessmentId' is not null or undefined
            assertParamExists('getAssessment', 'assessmentId', assessmentId)
            const localVarPath = `/customers/{id}/assessments/{assessment_id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"assessment_id"}}`, encodeURIComponent(String(assessmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary C1 题库拉取（按分龄组 + 维度）
         * @param {AgeGroup} ageGroup 
         * @param {Dimension} [dimension] 
         * @param {string} [version] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listScaleItemBanks: async (ageGroup: AgeGroup, dimension?: Dimension, version?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ageGroup' is not null or undefined
            assertParamExists('listScaleItemBanks', 'ageGroup', ageGroup)
            const localVarPath = `/scale-item-banks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (ageGroup !== undefined) {
                localVarQueryParameter['age_group'] = ageGroup;
            }

            if (dimension !== undefined) {
                localVarQueryParameter['dimension'] = dimension;
            }

            if (version !== undefined) {
                localVarQueryParameter['version'] = version;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 错误码：5001（题组量程 ≠ 0–4 / 题组非 symptom 向 / 缺分龄锁定）→ 提交阻断。 
         * @summary C2 基线评估提交（同源题组锁定）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {BaselineAssessmentRequest} baselineAssessmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitBaselineAssessment: async (id: string, baselineAssessmentRequest: BaselineAssessmentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('submitBaselineAssessment', 'id', id)
            // verify required parameter 'baselineAssessmentRequest' is not null or undefined
            assertParamExists('submitBaselineAssessment', 'baselineAssessmentRequest', baselineAssessmentRequest)
            const localVarPath = `/customers/{id}/assessments/baseline`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(baselineAssessmentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 🛑 两阶段模型第一阶段的落点：本端点只落【评估侧依据】 （cycle_assessment.verdict IS NULL = 待判定），不落任何判定结论。 判定由 F1（POST /cycle-assessments/{id}/verdicts）在同一行上补全。 错误码：5001（题组量程 ≠ 0–4 / 缺分龄锁定）；4001（同一 cycle_id 重复提交）。 
         * @summary C4 周期评估提交（每 7 次触发）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {CreateCycleAssessmentRequest} createCycleAssessmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitCycleAssessment: async (id: string, createCycleAssessmentRequest: CreateCycleAssessmentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('submitCycleAssessment', 'id', id)
            // verify required parameter 'createCycleAssessmentRequest' is not null or undefined
            assertParamExists('submitCycleAssessment', 'createCycleAssessmentRequest', createCycleAssessmentRequest)
            const localVarPath = `/customers/{id}/cycle-assessments`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCycleAssessmentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CApi - functional programming interface
 * @export
 */
export const CApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary C3 评估详情
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {string} assessmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAssessment(id: string, assessmentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAssessment(id, assessmentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CApi.getAssessment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary C1 题库拉取（按分龄组 + 维度）
         * @param {AgeGroup} ageGroup 
         * @param {Dimension} [dimension] 
         * @param {string} [version] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listScaleItemBanks(ageGroup: AgeGroup, dimension?: Dimension, version?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listScaleItemBanks(ageGroup, dimension, version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CApi.listScaleItemBanks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 错误码：5001（题组量程 ≠ 0–4 / 题组非 symptom 向 / 缺分龄锁定）→ 提交阻断。 
         * @summary C2 基线评估提交（同源题组锁定）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {BaselineAssessmentRequest} baselineAssessmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitBaselineAssessment(id: string, baselineAssessmentRequest: BaselineAssessmentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubmitBaselineAssessment200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitBaselineAssessment(id, baselineAssessmentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CApi.submitBaselineAssessment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 🛑 两阶段模型第一阶段的落点：本端点只落【评估侧依据】 （cycle_assessment.verdict IS NULL = 待判定），不落任何判定结论。 判定由 F1（POST /cycle-assessments/{id}/verdicts）在同一行上补全。 错误码：5001（题组量程 ≠ 0–4 / 缺分龄锁定）；4001（同一 cycle_id 重复提交）。 
         * @summary C4 周期评估提交（每 7 次触发）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {CreateCycleAssessmentRequest} createCycleAssessmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitCycleAssessment(id: string, createCycleAssessmentRequest: CreateCycleAssessmentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitCycleAssessment(id, createCycleAssessmentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CApi.submitCycleAssessment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CApi - factory interface
 * @export
 */
export const CApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CApiFp(configuration)
    return {
        /**
         * 
         * @summary C3 评估详情
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {string} assessmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAssessment(id: string, assessmentId: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.getAssessment(id, assessmentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary C1 题库拉取（按分龄组 + 维度）
         * @param {AgeGroup} ageGroup 
         * @param {Dimension} [dimension] 
         * @param {string} [version] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listScaleItemBanks(ageGroup: AgeGroup, dimension?: Dimension, version?: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.listScaleItemBanks(ageGroup, dimension, version, options).then((request) => request(axios, basePath));
        },
        /**
         * 错误码：5001（题组量程 ≠ 0–4 / 题组非 symptom 向 / 缺分龄锁定）→ 提交阻断。 
         * @summary C2 基线评估提交（同源题组锁定）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {BaselineAssessmentRequest} baselineAssessmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitBaselineAssessment(id: string, baselineAssessmentRequest: BaselineAssessmentRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubmitBaselineAssessment200Response> {
            return localVarFp.submitBaselineAssessment(id, baselineAssessmentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 🛑 两阶段模型第一阶段的落点：本端点只落【评估侧依据】 （cycle_assessment.verdict IS NULL = 待判定），不落任何判定结论。 判定由 F1（POST /cycle-assessments/{id}/verdicts）在同一行上补全。 错误码：5001（题组量程 ≠ 0–4 / 缺分龄锁定）；4001（同一 cycle_id 重复提交）。 
         * @summary C4 周期评估提交（每 7 次触发）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {CreateCycleAssessmentRequest} createCycleAssessmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitCycleAssessment(id: string, createCycleAssessmentRequest: CreateCycleAssessmentRequest, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.submitCycleAssessment(id, createCycleAssessmentRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CApi - object-oriented interface
 * @export
 * @class CApi
 * @extends {BaseAPI}
 */
export class CApi extends BaseAPI {
    /**
     * 
     * @summary C3 评估详情
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {string} assessmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CApi
     */
    public getAssessment(id: string, assessmentId: string, options?: RawAxiosRequestConfig) {
        return CApiFp(this.configuration).getAssessment(id, assessmentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary C1 题库拉取（按分龄组 + 维度）
     * @param {AgeGroup} ageGroup 
     * @param {Dimension} [dimension] 
     * @param {string} [version] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CApi
     */
    public listScaleItemBanks(ageGroup: AgeGroup, dimension?: Dimension, version?: string, options?: RawAxiosRequestConfig) {
        return CApiFp(this.configuration).listScaleItemBanks(ageGroup, dimension, version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 错误码：5001（题组量程 ≠ 0–4 / 题组非 symptom 向 / 缺分龄锁定）→ 提交阻断。 
     * @summary C2 基线评估提交（同源题组锁定）
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {BaselineAssessmentRequest} baselineAssessmentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CApi
     */
    public submitBaselineAssessment(id: string, baselineAssessmentRequest: BaselineAssessmentRequest, options?: RawAxiosRequestConfig) {
        return CApiFp(this.configuration).submitBaselineAssessment(id, baselineAssessmentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 🛑 两阶段模型第一阶段的落点：本端点只落【评估侧依据】 （cycle_assessment.verdict IS NULL = 待判定），不落任何判定结论。 判定由 F1（POST /cycle-assessments/{id}/verdicts）在同一行上补全。 错误码：5001（题组量程 ≠ 0–4 / 缺分龄锁定）；4001（同一 cycle_id 重复提交）。 
     * @summary C4 周期评估提交（每 7 次触发）
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {CreateCycleAssessmentRequest} createCycleAssessmentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CApi
     */
    public submitCycleAssessment(id: string, createCycleAssessmentRequest: CreateCycleAssessmentRequest, options?: RawAxiosRequestConfig) {
        return CApiFp(this.configuration).submitCycleAssessment(id, createCycleAssessmentRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

