/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateVisit200Response } from '../model';
// @ts-ignore
import type { DailyReportRequest } from '../model';
// @ts-ignore
import type { ResultEnvelope } from '../model';
// @ts-ignore
import type { SubmitDailyReport200Response } from '../model';
/**
 * DApi - axios parameter creator
 * @export
 */
export const DApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 🛑 本接口操作的是【门店级调理设备 device】（下行、可追责）， 与【客户级手环 band】是两本台账、不得合并。 
         * @summary D6 设备参数下发（需方案已审核）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDeviceDispatch: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/device-dispatches`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary D5-a 方案出具（回炉审核）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPlan: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/plans`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary D1 服务核销（四道闸门）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVisit: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createVisit', 'id', id)
            const localVarPath = `/customers/{id}/visits`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary D5-b 方案查阅
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPlan: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getPlan', 'id', id)
            const localVarPath = `/plans/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary D4 填报记录
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDailyReports: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listDailyReports', 'id', id)
            const localVarPath = `/customers/{id}/daily-reports`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary D2 服务记录（客户维度全局账本）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVisits: async (id: string, page?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listVisits', 'id', id)
            const localVarPath = `/customers/{id}/visits`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary D5-c 方案审核（退回必填 reason）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewPlan: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('reviewPlan', 'id', id)
            const localVarPath = `/plans/{id}/reviews`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary D3 每日填报提交
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {DailyReportRequest} dailyReportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitDailyReport: async (id: string, dailyReportRequest: DailyReportRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('submitDailyReport', 'id', id)
            // verify required parameter 'dailyReportRequest' is not null or undefined
            assertParamExists('submitDailyReport', 'dailyReportRequest', dailyReportRequest)
            const localVarPath = `/customers/{id}/daily-reports`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(dailyReportRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DApi - functional programming interface
 * @export
 */
export const DApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DApiAxiosParamCreator(configuration)
    return {
        /**
         * 🛑 本接口操作的是【门店级调理设备 device】（下行、可追责）， 与【客户级手环 band】是两本台账、不得合并。 
         * @summary D6 设备参数下发（需方案已审核）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDeviceDispatch(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDeviceDispatch(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DApi.createDeviceDispatch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary D5-a 方案出具（回炉审核）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createPlan(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createPlan(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DApi.createPlan']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary D1 服务核销（四道闸门）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVisit(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateVisit200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createVisit(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DApi.createVisit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary D5-b 方案查阅
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPlan(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPlan(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DApi.getPlan']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary D4 填报记录
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDailyReports(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDailyReports(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DApi.listDailyReports']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary D2 服务记录（客户维度全局账本）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listVisits(id: string, page?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listVisits(id, page, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DApi.listVisits']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary D5-c 方案审核（退回必填 reason）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async reviewPlan(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.reviewPlan(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DApi.reviewPlan']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary D3 每日填报提交
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {DailyReportRequest} dailyReportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async submitDailyReport(id: string, dailyReportRequest: DailyReportRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SubmitDailyReport200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.submitDailyReport(id, dailyReportRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DApi.submitDailyReport']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DApi - factory interface
 * @export
 */
export const DApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DApiFp(configuration)
    return {
        /**
         * 🛑 本接口操作的是【门店级调理设备 device】（下行、可追责）， 与【客户级手环 band】是两本台账、不得合并。 
         * @summary D6 设备参数下发（需方案已审核）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDeviceDispatch(options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.createDeviceDispatch(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary D5-a 方案出具（回炉审核）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createPlan(options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.createPlan(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary D1 服务核销（四道闸门）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVisit(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateVisit200Response> {
            return localVarFp.createVisit(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary D5-b 方案查阅
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPlan(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.getPlan(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary D4 填报记录
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDailyReports(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.listDailyReports(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary D2 服务记录（客户维度全局账本）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {number} [page] 
         * @param {number} [pageSize] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVisits(id: string, page?: number, pageSize?: number, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.listVisits(id, page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary D5-c 方案审核（退回必填 reason）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        reviewPlan(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.reviewPlan(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary D3 每日填报提交
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {DailyReportRequest} dailyReportRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        submitDailyReport(id: string, dailyReportRequest: DailyReportRequest, options?: RawAxiosRequestConfig): AxiosPromise<SubmitDailyReport200Response> {
            return localVarFp.submitDailyReport(id, dailyReportRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DApi - object-oriented interface
 * @export
 * @class DApi
 * @extends {BaseAPI}
 */
export class DApi extends BaseAPI {
    /**
     * 🛑 本接口操作的是【门店级调理设备 device】（下行、可追责）， 与【客户级手环 band】是两本台账、不得合并。 
     * @summary D6 设备参数下发（需方案已审核）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DApi
     */
    public createDeviceDispatch(options?: RawAxiosRequestConfig) {
        return DApiFp(this.configuration).createDeviceDispatch(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary D5-a 方案出具（回炉审核）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DApi
     */
    public createPlan(options?: RawAxiosRequestConfig) {
        return DApiFp(this.configuration).createPlan(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary D1 服务核销（四道闸门）
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DApi
     */
    public createVisit(id: string, options?: RawAxiosRequestConfig) {
        return DApiFp(this.configuration).createVisit(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary D5-b 方案查阅
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DApi
     */
    public getPlan(id: string, options?: RawAxiosRequestConfig) {
        return DApiFp(this.configuration).getPlan(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary D4 填报记录
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DApi
     */
    public listDailyReports(id: string, options?: RawAxiosRequestConfig) {
        return DApiFp(this.configuration).listDailyReports(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary D2 服务记录（客户维度全局账本）
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {number} [page] 
     * @param {number} [pageSize] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DApi
     */
    public listVisits(id: string, page?: number, pageSize?: number, options?: RawAxiosRequestConfig) {
        return DApiFp(this.configuration).listVisits(id, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary D5-c 方案审核（退回必填 reason）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DApi
     */
    public reviewPlan(id: string, options?: RawAxiosRequestConfig) {
        return DApiFp(this.configuration).reviewPlan(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary D3 每日填报提交
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {DailyReportRequest} dailyReportRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DApi
     */
    public submitDailyReport(id: string, dailyReportRequest: DailyReportRequest, options?: RawAxiosRequestConfig) {
        return DApiFp(this.configuration).submitDailyReport(id, dailyReportRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

