/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { GetBandDerived200Response } from '../model';
// @ts-ignore
import type { GetBandTelemetry200Response } from '../model';
// @ts-ignore
import type { ResultEnvelope } from '../model';
/**
 * EApi - axios parameter creator
 * @export
 */
export const EApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 🔴 客户 token 调本接口 → 403 VISIBILITY_DENIED，data.denied_fields 回显被拒字段名。 A3 applicable=False（无有效同步数据）时不返回 a3_value —— 避免\"0 值\"被误读为\"戴了 0 天\"。 
         * @summary E4 派生结果（A3 / AS / effect_verdict / 退款资格）—— 仅 staff
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBandDerived: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getBandDerived', 'id', id)
            const localVarPath = `/customers/{id}/band/derived`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary E3 手环原始数据 + 采集状态（四端按档裁剪）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBandTelemetry: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getBandTelemetry', 'id', id)
            const localVarPath = `/customers/{id}/band/telemetry`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EApi - functional programming interface
 * @export
 */
export const EApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EApiAxiosParamCreator(configuration)
    return {
        /**
         * 🔴 客户 token 调本接口 → 403 VISIBILITY_DENIED，data.denied_fields 回显被拒字段名。 A3 applicable=False（无有效同步数据）时不返回 a3_value —— 避免\"0 值\"被误读为\"戴了 0 天\"。 
         * @summary E4 派生结果（A3 / AS / effect_verdict / 退款资格）—— 仅 staff
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBandDerived(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetBandDerived200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBandDerived(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EApi.getBandDerived']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary E3 手环原始数据 + 采集状态（四端按档裁剪）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBandTelemetry(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetBandTelemetry200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBandTelemetry(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EApi.getBandTelemetry']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EApi - factory interface
 * @export
 */
export const EApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EApiFp(configuration)
    return {
        /**
         * 🔴 客户 token 调本接口 → 403 VISIBILITY_DENIED，data.denied_fields 回显被拒字段名。 A3 applicable=False（无有效同步数据）时不返回 a3_value —— 避免\"0 值\"被误读为\"戴了 0 天\"。 
         * @summary E4 派生结果（A3 / AS / effect_verdict / 退款资格）—— 仅 staff
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBandDerived(id: string, options?: RawAxiosRequestConfig): AxiosPromise<GetBandDerived200Response> {
            return localVarFp.getBandDerived(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary E3 手环原始数据 + 采集状态（四端按档裁剪）
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBandTelemetry(id: string, options?: RawAxiosRequestConfig): AxiosPromise<GetBandTelemetry200Response> {
            return localVarFp.getBandTelemetry(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EApi - object-oriented interface
 * @export
 * @class EApi
 * @extends {BaseAPI}
 */
export class EApi extends BaseAPI {
    /**
     * 🔴 客户 token 调本接口 → 403 VISIBILITY_DENIED，data.denied_fields 回显被拒字段名。 A3 applicable=False（无有效同步数据）时不返回 a3_value —— 避免\"0 值\"被误读为\"戴了 0 天\"。 
     * @summary E4 派生结果（A3 / AS / effect_verdict / 退款资格）—— 仅 staff
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EApi
     */
    public getBandDerived(id: string, options?: RawAxiosRequestConfig) {
        return EApiFp(this.configuration).getBandDerived(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary E3 手环原始数据 + 采集状态（四端按档裁剪）
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EApi
     */
    public getBandTelemetry(id: string, options?: RawAxiosRequestConfig) {
        return EApiFp(this.configuration).getBandTelemetry(id, options).then((request) => request(this.axios, this.basePath));
    }
}

