/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateVerdict200Response } from '../model';
// @ts-ignore
import type { CreateVerdictRequest } from '../model';
// @ts-ignore
import type { GetAuditCoverage200Response } from '../model';
// @ts-ignore
import type { ResultEnvelope } from '../model';
/**
 * FApi - axios parameter creator
 * @export
 */
export const FApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 🛑 A-2 起本端点的 requestBody 已捕获冻结（此前为已登记的契约缺口，客户端无法据契约生成请求）。 入参 = 判定所需的【原始事实】；判定分支（branch）由服务端按 effect_verdict × adherence_state × risk_flag 组合算出，**不得**由调用方传入 （PRD P0-12：判定出口不得混入单一 enum）。 threshold_version 是【断言位】而非取值位：可空（= 服务端填）； 非空时必须逐字等于服务端算出的内容寻址指纹，否则拒写 4001。 
         * @summary F1 判定结论落库（含依据快照 + 阈值版本）
         * @param {string} id 
         * @param {CreateVerdictRequest} createVerdictRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVerdict: async (id: string, createVerdictRequest: CreateVerdictRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createVerdict', 'id', id)
            // verify required parameter 'createVerdictRequest' is not null or undefined
            assertParamExists('createVerdict', 'createVerdictRequest', createVerdictRequest)
            const localVarPath = `/cycle-assessments/{id}/verdicts`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createVerdictRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 三数同显 = ECC 数 / 分母（结案疗程数）/ 可判定覆盖率，禁止只报 ECC 一个数。 ⚠️ f 相关字段（a3_observability）本版预留、不返回值（TBD）。 
         * @summary F4 可判定覆盖率（三数同显，Phase 2 P1-08）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditCoverage: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/audit/coverage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary F3 稽核信号（总部 / 区域；门店与加盟商不可见）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAuditSignals: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/audit/signals`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 🔴 客户与调理师端一律 403 VISIBILITY_DENIED。
         * @summary F2 判定历史
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVerdicts: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listVerdicts', 'id', id)
            const localVarPath = `/customers/{id}/verdicts`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FApi - functional programming interface
 * @export
 */
export const FApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FApiAxiosParamCreator(configuration)
    return {
        /**
         * 🛑 A-2 起本端点的 requestBody 已捕获冻结（此前为已登记的契约缺口，客户端无法据契约生成请求）。 入参 = 判定所需的【原始事实】；判定分支（branch）由服务端按 effect_verdict × adherence_state × risk_flag 组合算出，**不得**由调用方传入 （PRD P0-12：判定出口不得混入单一 enum）。 threshold_version 是【断言位】而非取值位：可空（= 服务端填）； 非空时必须逐字等于服务端算出的内容寻址指纹，否则拒写 4001。 
         * @summary F1 判定结论落库（含依据快照 + 阈值版本）
         * @param {string} id 
         * @param {CreateVerdictRequest} createVerdictRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createVerdict(id: string, createVerdictRequest: CreateVerdictRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateVerdict200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createVerdict(id, createVerdictRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FApi.createVerdict']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 三数同显 = ECC 数 / 分母（结案疗程数）/ 可判定覆盖率，禁止只报 ECC 一个数。 ⚠️ f 相关字段（a3_observability）本版预留、不返回值（TBD）。 
         * @summary F4 可判定覆盖率（三数同显，Phase 2 P1-08）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuditCoverage(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetAuditCoverage200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuditCoverage(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FApi.getAuditCoverage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary F3 稽核信号（总部 / 区域；门店与加盟商不可见）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAuditSignals(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAuditSignals(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FApi.listAuditSignals']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 🔴 客户与调理师端一律 403 VISIBILITY_DENIED。
         * @summary F2 判定历史
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listVerdicts(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listVerdicts(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FApi.listVerdicts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FApi - factory interface
 * @export
 */
export const FApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FApiFp(configuration)
    return {
        /**
         * 🛑 A-2 起本端点的 requestBody 已捕获冻结（此前为已登记的契约缺口，客户端无法据契约生成请求）。 入参 = 判定所需的【原始事实】；判定分支（branch）由服务端按 effect_verdict × adherence_state × risk_flag 组合算出，**不得**由调用方传入 （PRD P0-12：判定出口不得混入单一 enum）。 threshold_version 是【断言位】而非取值位：可空（= 服务端填）； 非空时必须逐字等于服务端算出的内容寻址指纹，否则拒写 4001。 
         * @summary F1 判定结论落库（含依据快照 + 阈值版本）
         * @param {string} id 
         * @param {CreateVerdictRequest} createVerdictRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createVerdict(id: string, createVerdictRequest: CreateVerdictRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateVerdict200Response> {
            return localVarFp.createVerdict(id, createVerdictRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 三数同显 = ECC 数 / 分母（结案疗程数）/ 可判定覆盖率，禁止只报 ECC 一个数。 ⚠️ f 相关字段（a3_observability）本版预留、不返回值（TBD）。 
         * @summary F4 可判定覆盖率（三数同显，Phase 2 P1-08）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditCoverage(options?: RawAxiosRequestConfig): AxiosPromise<GetAuditCoverage200Response> {
            return localVarFp.getAuditCoverage(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary F3 稽核信号（总部 / 区域；门店与加盟商不可见）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAuditSignals(options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.listAuditSignals(options).then((request) => request(axios, basePath));
        },
        /**
         * 🔴 客户与调理师端一律 403 VISIBILITY_DENIED。
         * @summary F2 判定历史
         * @param {string} id 客户 ID（服务端从 token 校验租户归属）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listVerdicts(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.listVerdicts(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FApi - object-oriented interface
 * @export
 * @class FApi
 * @extends {BaseAPI}
 */
export class FApi extends BaseAPI {
    /**
     * 🛑 A-2 起本端点的 requestBody 已捕获冻结（此前为已登记的契约缺口，客户端无法据契约生成请求）。 入参 = 判定所需的【原始事实】；判定分支（branch）由服务端按 effect_verdict × adherence_state × risk_flag 组合算出，**不得**由调用方传入 （PRD P0-12：判定出口不得混入单一 enum）。 threshold_version 是【断言位】而非取值位：可空（= 服务端填）； 非空时必须逐字等于服务端算出的内容寻址指纹，否则拒写 4001。 
     * @summary F1 判定结论落库（含依据快照 + 阈值版本）
     * @param {string} id 
     * @param {CreateVerdictRequest} createVerdictRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FApi
     */
    public createVerdict(id: string, createVerdictRequest: CreateVerdictRequest, options?: RawAxiosRequestConfig) {
        return FApiFp(this.configuration).createVerdict(id, createVerdictRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 三数同显 = ECC 数 / 分母（结案疗程数）/ 可判定覆盖率，禁止只报 ECC 一个数。 ⚠️ f 相关字段（a3_observability）本版预留、不返回值（TBD）。 
     * @summary F4 可判定覆盖率（三数同显，Phase 2 P1-08）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FApi
     */
    public getAuditCoverage(options?: RawAxiosRequestConfig) {
        return FApiFp(this.configuration).getAuditCoverage(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary F3 稽核信号（总部 / 区域；门店与加盟商不可见）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FApi
     */
    public listAuditSignals(options?: RawAxiosRequestConfig) {
        return FApiFp(this.configuration).listAuditSignals(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 🔴 客户与调理师端一律 403 VISIBILITY_DENIED。
     * @summary F2 判定历史
     * @param {string} id 客户 ID（服务端从 token 校验租户归属）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FApi
     */
    public listVerdicts(id: string, options?: RawAxiosRequestConfig) {
        return FApiFp(this.configuration).listVerdicts(id, options).then((request) => request(this.axios, this.basePath));
    }
}

