/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateRefund200Response } from '../model';
// @ts-ignore
import type { CreateRefundReceipt200Response } from '../model';
// @ts-ignore
import type { RefundCreateRequest } from '../model';
// @ts-ignore
import type { ResultEnvelope } from '../model';
/**
 * GApi - axios parameter creator
 * @export
 */
export const GApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary G4 审批（出口集中；代录者不可审批）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveRefund: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('approveRefund', 'id', id)
            const localVarPath = `/refunds/{id}/approvals`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary G1 代录客户退款诉求（发起方 = 经络师 / 门店负责人）
         * @param {RefundCreateRequest} refundCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRefund: async (refundCreateRequest: RefundCreateRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'refundCreateRequest' is not null or undefined
            assertParamExists('createRefund', 'refundCreateRequest', refundCreateRequest)
            const localVarPath = `/refunds`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(refundCreateRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary G5 回执（三态留痕）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRefundReceipt: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createRefundReceipt', 'id', id)
            const localVarPath = `/refunds/{id}/receipts`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary G3 挽留记录（挽留记录必填；入口 B 不经挽留）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRetention: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createRetention', 'id', id)
            const localVarPath = `/refunds/{id}/retentions`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary G2 退款工单详情
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRefund: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getRefund', 'id', id)
            const localVarPath = `/refunds/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * GApi - functional programming interface
 * @export
 */
export const GApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = GApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary G4 审批（出口集中；代录者不可审批）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async approveRefund(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.approveRefund(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GApi.approveRefund']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary G1 代录客户退款诉求（发起方 = 经络师 / 门店负责人）
         * @param {RefundCreateRequest} refundCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRefund(refundCreateRequest: RefundCreateRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateRefund200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRefund(refundCreateRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GApi.createRefund']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary G5 回执（三态留痕）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRefundReceipt(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateRefundReceipt200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRefundReceipt(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GApi.createRefundReceipt']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary G3 挽留记录（挽留记录必填；入口 B 不经挽留）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createRetention(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createRetention(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GApi.createRetention']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary G2 退款工单详情
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRefund(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRefund(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['GApi.getRefund']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * GApi - factory interface
 * @export
 */
export const GApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = GApiFp(configuration)
    return {
        /**
         * 
         * @summary G4 审批（出口集中；代录者不可审批）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        approveRefund(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.approveRefund(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary G1 代录客户退款诉求（发起方 = 经络师 / 门店负责人）
         * @param {RefundCreateRequest} refundCreateRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRefund(refundCreateRequest: RefundCreateRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateRefund200Response> {
            return localVarFp.createRefund(refundCreateRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary G5 回执（三态留痕）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRefundReceipt(id: string, options?: RawAxiosRequestConfig): AxiosPromise<CreateRefundReceipt200Response> {
            return localVarFp.createRefundReceipt(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary G3 挽留记录（挽留记录必填；入口 B 不经挽留）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createRetention(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.createRetention(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary G2 退款工单详情
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRefund(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.getRefund(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * GApi - object-oriented interface
 * @export
 * @class GApi
 * @extends {BaseAPI}
 */
export class GApi extends BaseAPI {
    /**
     * 
     * @summary G4 审批（出口集中；代录者不可审批）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GApi
     */
    public approveRefund(id: string, options?: RawAxiosRequestConfig) {
        return GApiFp(this.configuration).approveRefund(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary G1 代录客户退款诉求（发起方 = 经络师 / 门店负责人）
     * @param {RefundCreateRequest} refundCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GApi
     */
    public createRefund(refundCreateRequest: RefundCreateRequest, options?: RawAxiosRequestConfig) {
        return GApiFp(this.configuration).createRefund(refundCreateRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary G5 回执（三态留痕）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GApi
     */
    public createRefundReceipt(id: string, options?: RawAxiosRequestConfig) {
        return GApiFp(this.configuration).createRefundReceipt(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary G3 挽留记录（挽留记录必填；入口 B 不经挽留）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GApi
     */
    public createRetention(id: string, options?: RawAxiosRequestConfig) {
        return GApiFp(this.configuration).createRetention(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary G2 退款工单详情
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof GApi
     */
    public getRefund(id: string, options?: RawAxiosRequestConfig) {
        return GApiFp(this.configuration).getRefund(id, options).then((request) => request(this.axios, this.basePath));
    }
}

