/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { DocType } from '../model';
// @ts-ignore
import type { ResultEnvelope } from '../model';
/**
 * IApi - axios parameter creator
 * @export
 */
export const IApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary I2 新建（source_type=editor，JSON 正文）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDocTemplate: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/doc-templates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary I4 新版本（editor / upload 均可；不可覆盖）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDocTemplateVersion: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('createDocTemplateVersion', 'id', id)
            const localVarPath = `/doc-templates/{id}/versions`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary I7 下载原件（上传形态用）—— 仅超管
         * @param {string} id 
         * @param {number} version 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadDocTemplate: async (id: string, version: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('downloadDocTemplate', 'id', id)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('downloadDocTemplate', 'version', version)
            const localVarPath = `/doc-templates/{id}/download`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (version !== undefined) {
                localVarQueryParameter['version'] = version;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary I5 版本列表（含 source_type / file_hash / change_reason，不含正文）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDocTemplateVersions: async (id: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('listDocTemplateVersions', 'id', id)
            const localVarPath = `/doc-templates/{id}/versions`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 门店负责人 / 区域督导只读（仅 is_active=true，仅 title + version，不含 content / file_ref）。
         * @summary I1 模板列表（按 doc_type 过滤）
         * @param {DocType} [docType] 
         * @param {boolean} [isActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDocTemplates: async (docType?: DocType, isActive?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/doc-templates`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (docType !== undefined) {
                localVarQueryParameter['doc_type'] = docType;
            }

            if (isActive !== undefined) {
                localVarQueryParameter['is_active'] = isActive;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary I6 发布（置 is_active=true，同 doc_type 其他版本置 false）
         * @param {string} id 
         * @param {number} version 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publishDocTemplateVersion: async (id: string, version: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('publishDocTemplateVersion', 'id', id)
            // verify required parameter 'version' is not null or undefined
            assertParamExists('publishDocTemplateVersion', 'version', version)
            const localVarPath = `/doc-templates/{id}/versions/{version}/publish`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)))
                .replace(`{${"version"}}`, encodeURIComponent(String(version)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 上传约束：mime_type 仅允许三值（application/pdf / application/vnd.openxmlformats-officedocument.wordprocessingml.document / text/markdown）； file_size ≤ 10 MiB；落盘前先算 file_hash（SHA-256 hex）， 同 <tenant, doc_type> 下同 hash 重复上传 → 返回已有版本号（幂等返回 4002）。  🛑 反病毒 / 反脚本：上传文件不得作为可执行内容被服务端解析执行；    DOCX 不得解压执行宏（只做字节存储 + 哈希，不做宏解析）。 
         * @summary I3 上传（multipart/form-data → source_type=upload）
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadDocTemplate: async (file?: File, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/doc-templates/uploads`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * IApi - functional programming interface
 * @export
 */
export const IApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = IApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary I2 新建（source_type=editor，JSON 正文）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDocTemplate(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDocTemplate(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IApi.createDocTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary I4 新版本（editor / upload 均可；不可覆盖）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDocTemplateVersion(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDocTemplateVersion(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IApi.createDocTemplateVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary I7 下载原件（上传形态用）—— 仅超管
         * @param {string} id 
         * @param {number} version 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async downloadDocTemplate(id: string, version: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.downloadDocTemplate(id, version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IApi.downloadDocTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary I5 版本列表（含 source_type / file_hash / change_reason，不含正文）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDocTemplateVersions(id: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDocTemplateVersions(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IApi.listDocTemplateVersions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 门店负责人 / 区域督导只读（仅 is_active=true，仅 title + version，不含 content / file_ref）。
         * @summary I1 模板列表（按 doc_type 过滤）
         * @param {DocType} [docType] 
         * @param {boolean} [isActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDocTemplates(docType?: DocType, isActive?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDocTemplates(docType, isActive, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IApi.listDocTemplates']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary I6 发布（置 is_active=true，同 doc_type 其他版本置 false）
         * @param {string} id 
         * @param {number} version 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async publishDocTemplateVersion(id: string, version: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.publishDocTemplateVersion(id, version, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IApi.publishDocTemplateVersion']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 上传约束：mime_type 仅允许三值（application/pdf / application/vnd.openxmlformats-officedocument.wordprocessingml.document / text/markdown）； file_size ≤ 10 MiB；落盘前先算 file_hash（SHA-256 hex）， 同 <tenant, doc_type> 下同 hash 重复上传 → 返回已有版本号（幂等返回 4002）。  🛑 反病毒 / 反脚本：上传文件不得作为可执行内容被服务端解析执行；    DOCX 不得解压执行宏（只做字节存储 + 哈希，不做宏解析）。 
         * @summary I3 上传（multipart/form-data → source_type=upload）
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async uploadDocTemplate(file?: File, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResultEnvelope>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.uploadDocTemplate(file, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['IApi.uploadDocTemplate']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * IApi - factory interface
 * @export
 */
export const IApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = IApiFp(configuration)
    return {
        /**
         * 
         * @summary I2 新建（source_type=editor，JSON 正文）
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDocTemplate(options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.createDocTemplate(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary I4 新版本（editor / upload 均可；不可覆盖）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDocTemplateVersion(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.createDocTemplateVersion(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary I7 下载原件（上传形态用）—— 仅超管
         * @param {string} id 
         * @param {number} version 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        downloadDocTemplate(id: string, version: number, options?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.downloadDocTemplate(id, version, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary I5 版本列表（含 source_type / file_hash / change_reason，不含正文）
         * @param {string} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDocTemplateVersions(id: string, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.listDocTemplateVersions(id, options).then((request) => request(axios, basePath));
        },
        /**
         * 门店负责人 / 区域督导只读（仅 is_active=true，仅 title + version，不含 content / file_ref）。
         * @summary I1 模板列表（按 doc_type 过滤）
         * @param {DocType} [docType] 
         * @param {boolean} [isActive] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDocTemplates(docType?: DocType, isActive?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.listDocTemplates(docType, isActive, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary I6 发布（置 is_active=true，同 doc_type 其他版本置 false）
         * @param {string} id 
         * @param {number} version 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        publishDocTemplateVersion(id: string, version: number, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.publishDocTemplateVersion(id, version, options).then((request) => request(axios, basePath));
        },
        /**
         * 上传约束：mime_type 仅允许三值（application/pdf / application/vnd.openxmlformats-officedocument.wordprocessingml.document / text/markdown）； file_size ≤ 10 MiB；落盘前先算 file_hash（SHA-256 hex）， 同 <tenant, doc_type> 下同 hash 重复上传 → 返回已有版本号（幂等返回 4002）。  🛑 反病毒 / 反脚本：上传文件不得作为可执行内容被服务端解析执行；    DOCX 不得解压执行宏（只做字节存储 + 哈希，不做宏解析）。 
         * @summary I3 上传（multipart/form-data → source_type=upload）
         * @param {File} [file] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        uploadDocTemplate(file?: File, options?: RawAxiosRequestConfig): AxiosPromise<ResultEnvelope> {
            return localVarFp.uploadDocTemplate(file, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * IApi - object-oriented interface
 * @export
 * @class IApi
 * @extends {BaseAPI}
 */
export class IApi extends BaseAPI {
    /**
     * 
     * @summary I2 新建（source_type=editor，JSON 正文）
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IApi
     */
    public createDocTemplate(options?: RawAxiosRequestConfig) {
        return IApiFp(this.configuration).createDocTemplate(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary I4 新版本（editor / upload 均可；不可覆盖）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IApi
     */
    public createDocTemplateVersion(id: string, options?: RawAxiosRequestConfig) {
        return IApiFp(this.configuration).createDocTemplateVersion(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary I7 下载原件（上传形态用）—— 仅超管
     * @param {string} id 
     * @param {number} version 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IApi
     */
    public downloadDocTemplate(id: string, version: number, options?: RawAxiosRequestConfig) {
        return IApiFp(this.configuration).downloadDocTemplate(id, version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary I5 版本列表（含 source_type / file_hash / change_reason，不含正文）
     * @param {string} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IApi
     */
    public listDocTemplateVersions(id: string, options?: RawAxiosRequestConfig) {
        return IApiFp(this.configuration).listDocTemplateVersions(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 门店负责人 / 区域督导只读（仅 is_active=true，仅 title + version，不含 content / file_ref）。
     * @summary I1 模板列表（按 doc_type 过滤）
     * @param {DocType} [docType] 
     * @param {boolean} [isActive] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IApi
     */
    public listDocTemplates(docType?: DocType, isActive?: boolean, options?: RawAxiosRequestConfig) {
        return IApiFp(this.configuration).listDocTemplates(docType, isActive, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary I6 发布（置 is_active=true，同 doc_type 其他版本置 false）
     * @param {string} id 
     * @param {number} version 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IApi
     */
    public publishDocTemplateVersion(id: string, version: number, options?: RawAxiosRequestConfig) {
        return IApiFp(this.configuration).publishDocTemplateVersion(id, version, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 上传约束：mime_type 仅允许三值（application/pdf / application/vnd.openxmlformats-officedocument.wordprocessingml.document / text/markdown）； file_size ≤ 10 MiB；落盘前先算 file_hash（SHA-256 hex）， 同 <tenant, doc_type> 下同 hash 重复上传 → 返回已有版本号（幂等返回 4002）。  🛑 反病毒 / 反脚本：上传文件不得作为可执行内容被服务端解析执行；    DOCX 不得解压执行宏（只做字节存储 + 哈希，不做宏解析）。 
     * @summary I3 上传（multipart/form-data → source_type=upload）
     * @param {File} [file] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof IApi
     */
    public uploadDocTemplate(file?: File, options?: RawAxiosRequestConfig) {
        return IApiFp(this.configuration).uploadDocTemplate(file, options).then((request) => request(this.axios, this.basePath));
    }
}

