/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DyClientSdk);
  }
}(this, function(expect, DyClientSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DyClientSdk.AuthMeDataBandVisibility();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AuthMeDataBandVisibility', function() {
    it('should create an instance of AuthMeDataBandVisibility', function() {
      // uncomment below and update the code to test AuthMeDataBandVisibility
      //var instance = new DyClientSdk.AuthMeDataBandVisibility();
      //expect(instance).to.be.a(DyClientSdk.AuthMeDataBandVisibility);
    });

    it('should have the property fieldGroup1Raw (base name: "field_group_1_raw")', function() {
      // uncomment below and update the code to test the property fieldGroup1Raw
      //var instance = new DyClientSdk.AuthMeDataBandVisibility();
      //expect(instance).to.be();
    });

    it('should have the property fieldGroup2Status (base name: "field_group_2_status")', function() {
      // uncomment below and update the code to test the property fieldGroup2Status
      //var instance = new DyClientSdk.AuthMeDataBandVisibility();
      //expect(instance).to.be();
    });

    it('should have the property fieldGroup3GapReason (base name: "field_group_3_gap_reason")', function() {
      // uncomment below and update the code to test the property fieldGroup3GapReason
      //var instance = new DyClientSdk.AuthMeDataBandVisibility();
      //expect(instance).to.be();
    });

    it('should have the property fieldGroup4Derived (base name: "field_group_4_derived")', function() {
      // uncomment below and update the code to test the property fieldGroup4Derived
      //var instance = new DyClientSdk.AuthMeDataBandVisibility();
      //expect(instance).to.be();
    });

  });

}));
