/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DyClientSdk);
  }
}(this, function(expect, DyClientSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DyClientSdk.BandSyncBatchRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BandSyncBatchRequest', function() {
    it('should create an instance of BandSyncBatchRequest', function() {
      // uncomment below and update the code to test BandSyncBatchRequest
      //var instance = new DyClientSdk.BandSyncBatchRequest();
      //expect(instance).to.be.a(DyClientSdk.BandSyncBatchRequest);
    });

    it('should have the property deviceId (base name: "device_id")', function() {
      // uncomment below and update the code to test the property deviceId
      //var instance = new DyClientSdk.BandSyncBatchRequest();
      //expect(instance).to.be();
    });

    it('should have the property customerId (base name: "customer_id")', function() {
      // uncomment below and update the code to test the property customerId
      //var instance = new DyClientSdk.BandSyncBatchRequest();
      //expect(instance).to.be();
    });

    it('should have the property batchNo (base name: "batch_no")', function() {
      // uncomment below and update the code to test the property batchNo
      //var instance = new DyClientSdk.BandSyncBatchRequest();
      //expect(instance).to.be();
    });

    it('should have the property trigger (base name: "trigger")', function() {
      // uncomment below and update the code to test the property trigger
      //var instance = new DyClientSdk.BandSyncBatchRequest();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new DyClientSdk.BandSyncBatchRequest();
      //expect(instance).to.be();
    });

    it('should have the property syncedAt (base name: "synced_at")', function() {
      // uncomment below and update the code to test the property syncedAt
      //var instance = new DyClientSdk.BandSyncBatchRequest();
      //expect(instance).to.be();
    });

    it('should have the property lastSuccessDate (base name: "last_success_date")', function() {
      // uncomment below and update the code to test the property lastSuccessDate
      //var instance = new DyClientSdk.BandSyncBatchRequest();
      //expect(instance).to.be();
    });

    it('should have the property failReasonClass (base name: "fail_reason_class")', function() {
      // uncomment below and update the code to test the property failReasonClass
      //var instance = new DyClientSdk.BandSyncBatchRequest();
      //expect(instance).to.be();
    });

    it('should have the property nextAction (base name: "next_action")', function() {
      // uncomment below and update the code to test the property nextAction
      //var instance = new DyClientSdk.BandSyncBatchRequest();
      //expect(instance).to.be();
    });

  });

}));
