/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DyClientSdk);
  }
}(this, function(expect, DyClientSdk) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DyClientSdk.CustomerDetailData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomerDetailData', function() {
    it('should create an instance of CustomerDetailData', function() {
      // uncomment below and update the code to test CustomerDetailData
      //var instance = new DyClientSdk.CustomerDetailData();
      //expect(instance).to.be.a(DyClientSdk.CustomerDetailData);
    });

    it('should have the property customerId (base name: "customer_id")', function() {
      // uncomment below and update the code to test the property customerId
      //var instance = new DyClientSdk.CustomerDetailData();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new DyClientSdk.CustomerDetailData();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new DyClientSdk.CustomerDetailData();
      //expect(instance).to.be();
    });

    it('should have the property age (base name: "age")', function() {
      // uncomment below and update the code to test the property age
      //var instance = new DyClientSdk.CustomerDetailData();
      //expect(instance).to.be();
    });

    it('should have the property intakeProfile (base name: "intake_profile")', function() {
      // uncomment below and update the code to test the property intakeProfile
      //var instance = new DyClientSdk.CustomerDetailData();
      //expect(instance).to.be();
    });

    it('should have the property screeningResult (base name: "screening_result")', function() {
      // uncomment below and update the code to test the property screeningResult
      //var instance = new DyClientSdk.CustomerDetailData();
      //expect(instance).to.be();
    });

    it('should have the property bandWillingness (base name: "band_willingness")', function() {
      // uncomment below and update the code to test the property bandWillingness
      //var instance = new DyClientSdk.CustomerDetailData();
      //expect(instance).to.be();
    });

    it('should have the property ownerStoreId (base name: "owner_store_id")', function() {
      // uncomment below and update the code to test the property ownerStoreId
      //var instance = new DyClientSdk.CustomerDetailData();
      //expect(instance).to.be();
    });

    it('should have the property servingStoreId (base name: "serving_store_id")', function() {
      // uncomment below and update the code to test the property servingStoreId
      //var instance = new DyClientSdk.CustomerDetailData();
      //expect(instance).to.be();
    });

    it('should have the property effectVerdict (base name: "effect_verdict")', function() {
      // uncomment below and update the code to test the property effectVerdict
      //var instance = new DyClientSdk.CustomerDetailData();
      //expect(instance).to.be();
    });

    it('should have the property asValue (base name: "as_value")', function() {
      // uncomment below and update the code to test the property asValue
      //var instance = new DyClientSdk.CustomerDetailData();
      //expect(instance).to.be();
    });

  });

}));
