/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AgeGroup.
* @enum {}
* @readonly
*/
export default class AgeGroup {
    
        /**
         * value: "男16-32"
         * @const
         */
        "男16-32" = "男16-32";

    
        /**
         * value: "男33-40"
         * @const
         */
        "男33-40" = "男33-40";

    
        /**
         * value: "男41-48"
         * @const
         */
        "男41-48" = "男41-48";

    
        /**
         * value: "男49以上"
         * @const
         */
        "男49以上" = "男49以上";

    
        /**
         * value: "女14-28"
         * @const
         */
        "女14-28" = "女14-28";

    
        /**
         * value: "女29-35"
         * @const
         */
        "女29-35" = "女29-35";

    
        /**
         * value: "女36-42"
         * @const
         */
        "女36-42" = "女36-42";

    
        /**
         * value: "女43-49以上"
         * @const
         */
        "女43-49以上" = "女43-49以上";

    

    /**
    * Returns a <code>AgeGroup</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AgeGroup} The enum <code>AgeGroup</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

