/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthMeDataStoreScope model module.
 * @module model/AuthMeDataStoreScope
 * @version api-contract-v1.0.0
 */
class AuthMeDataStoreScope {
    /**
     * Constructs a new <code>AuthMeDataStoreScope</code>.
     * @alias module:model/AuthMeDataStoreScope
     */
    constructor() { 
        
        AuthMeDataStoreScope.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthMeDataStoreScope</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthMeDataStoreScope} obj Optional instance to populate.
     * @return {module:model/AuthMeDataStoreScope} The populated <code>AuthMeDataStoreScope</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthMeDataStoreScope();

            if (data.hasOwnProperty('row_level')) {
                obj['row_level'] = ApiClient.convertToType(data['row_level'], 'String');
            }
            if (data.hasOwnProperty('store_ids')) {
                obj['store_ids'] = ApiClient.convertToType(data['store_ids'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthMeDataStoreScope</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthMeDataStoreScope</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['row_level'] && !(typeof data['row_level'] === 'string' || data['row_level'] instanceof String)) {
            throw new Error("Expected the field `row_level` to be a primitive type in the JSON string but got " + data['row_level']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['store_ids'])) {
            throw new Error("Expected the field `store_ids` to be an array in the JSON data but got " + data['store_ids']);
        }

        return true;
    }


}



/**
 * @member {module:model/AuthMeDataStoreScope.RowLevelEnum} row_level
 */
AuthMeDataStoreScope.prototype['row_level'] = undefined;

/**
 * @member {Array.<String>} store_ids
 */
AuthMeDataStoreScope.prototype['store_ids'] = undefined;





/**
 * Allowed values for the <code>row_level</code> property.
 * @enum {String}
 * @readonly
 */
AuthMeDataStoreScope['RowLevelEnum'] = {

    /**
     * value: "own_store"
     * @const
     */
    "own_store": "own_store",

    /**
     * value: "region"
     * @const
     */
    "region": "region",

    /**
     * value: "all"
     * @const
     */
    "all": "all"
};



export default AuthMeDataStoreScope;

