/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AuthMeData from './AuthMeData';
import ResultEnvelope from './ResultEnvelope';

/**
 * The AuthMe200Response model module.
 * @module model/AuthMe200Response
 * @version api-contract-v1.0.0
 */
class AuthMe200Response {
    /**
     * Constructs a new <code>AuthMe200Response</code>.
     * @alias module:model/AuthMe200Response
     * @implements module:model/ResultEnvelope
     * @param code {Number} 0 = 成功；非 0 见 x-error-codes
     * @param message {String} 面向开发者，不得直接渲染给客户（客户端有自己的 code → copy 映射）
     * @param traceId {String} 
     */
    constructor(code, message, traceId) { 
        ResultEnvelope.initialize(this, code, message, traceId);
        AuthMe200Response.initialize(this, code, message, traceId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, message, traceId) { 
        obj['code'] = code;
        obj['message'] = message;
        obj['trace_id'] = traceId;
    }

    /**
     * Constructs a <code>AuthMe200Response</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthMe200Response} obj Optional instance to populate.
     * @return {module:model/AuthMe200Response} The populated <code>AuthMe200Response</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthMe200Response();
            ResultEnvelope.constructFromObject(data, obj);

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'Number');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('data')) {
                obj['data'] = AuthMeData.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('trace_id')) {
                obj['trace_id'] = ApiClient.convertToType(data['trace_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthMe200Response</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthMe200Response</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuthMe200Response.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // validate the optional field `data`
        if (data['data']) { // data not null
          AuthMeData.validateJSON(data['data']);
        }
        // ensure the json data is a string
        if (data['trace_id'] && !(typeof data['trace_id'] === 'string' || data['trace_id'] instanceof String)) {
            throw new Error("Expected the field `trace_id` to be a primitive type in the JSON string but got " + data['trace_id']);
        }

        return true;
    }


}

AuthMe200Response.RequiredProperties = ["code", "message", "trace_id"];

/**
 * 0 = 成功；非 0 见 x-error-codes
 * @member {Number} code
 */
AuthMe200Response.prototype['code'] = undefined;

/**
 * 面向开发者，不得直接渲染给客户（客户端有自己的 code → copy 映射）
 * @member {String} message
 */
AuthMe200Response.prototype['message'] = undefined;

/**
 * @member {module:model/AuthMeData} data
 */
AuthMe200Response.prototype['data'] = undefined;

/**
 * @member {String} trace_id
 */
AuthMe200Response.prototype['trace_id'] = undefined;


// Implement ResultEnvelope interface:
/**
 * 0 = 成功；非 0 见 x-error-codes
 * @member {Number} code
 */
ResultEnvelope.prototype['code'] = undefined;
/**
 * 面向开发者，不得直接渲染给客户（客户端有自己的 code → copy 映射）
 * @member {String} message
 */
ResultEnvelope.prototype['message'] = undefined;
/**
 * code != 0 时为空
 * @member {Object} data
 */
ResultEnvelope.prototype['data'] = undefined;
/**
 * @member {String} trace_id
 */
ResultEnvelope.prototype['trace_id'] = undefined;




export default AuthMe200Response;

