/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthLoginRequest model module.
 * @module model/AuthLoginRequest
 * @version api-contract-v1.0.0
 */
class AuthLoginRequest {
    /**
     * Constructs a new <code>AuthLoginRequest</code>.
     * @alias module:model/AuthLoginRequest
     * @param account {String} 员工号 / 客户 openid 绑定号
     * @param credential {String} 密码 / 短信码
     * @param clientEnd {module:model/AuthLoginRequest.ClientEndEnum} 
     */
    constructor(account, credential, clientEnd) { 
        
        AuthLoginRequest.initialize(this, account, credential, clientEnd);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, account, credential, clientEnd) { 
        obj['account'] = account;
        obj['credential'] = credential;
        obj['client_end'] = clientEnd;
    }

    /**
     * Constructs a <code>AuthLoginRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthLoginRequest} obj Optional instance to populate.
     * @return {module:model/AuthLoginRequest} The populated <code>AuthLoginRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthLoginRequest();

            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('credential')) {
                obj['credential'] = ApiClient.convertToType(data['credential'], 'String');
            }
            if (data.hasOwnProperty('client_end')) {
                obj['client_end'] = ApiClient.convertToType(data['client_end'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthLoginRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthLoginRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of AuthLoginRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['account'] && !(typeof data['account'] === 'string' || data['account'] instanceof String)) {
            throw new Error("Expected the field `account` to be a primitive type in the JSON string but got " + data['account']);
        }
        // ensure the json data is a string
        if (data['credential'] && !(typeof data['credential'] === 'string' || data['credential'] instanceof String)) {
            throw new Error("Expected the field `credential` to be a primitive type in the JSON string but got " + data['credential']);
        }
        // ensure the json data is a string
        if (data['client_end'] && !(typeof data['client_end'] === 'string' || data['client_end'] instanceof String)) {
            throw new Error("Expected the field `client_end` to be a primitive type in the JSON string but got " + data['client_end']);
        }

        return true;
    }


}

AuthLoginRequest.RequiredProperties = ["account", "credential", "client_end"];

/**
 * 员工号 / 客户 openid 绑定号
 * @member {String} account
 */
AuthLoginRequest.prototype['account'] = undefined;

/**
 * 密码 / 短信码
 * @member {String} credential
 */
AuthLoginRequest.prototype['credential'] = undefined;

/**
 * @member {module:model/AuthLoginRequest.ClientEndEnum} client_end
 */
AuthLoginRequest.prototype['client_end'] = undefined;





/**
 * Allowed values for the <code>client_end</code> property.
 * @enum {String}
 * @readonly
 */
AuthLoginRequest['ClientEndEnum'] = {

    /**
     * value: "mp"
     * @const
     */
    "mp": "mp",

    /**
     * value: "app"
     * @const
     */
    "app": "app",

    /**
     * value: "web"
     * @const
     */
    "web": "web"
};



export default AuthLoginRequest;

