/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AuthMeDataBandVisibility model module.
 * @module model/AuthMeDataBandVisibility
 * @version api-contract-v1.0.0
 */
class AuthMeDataBandVisibility {
    /**
     * Constructs a new <code>AuthMeDataBandVisibility</code>.
     * 字段组档位布尔值（声明，不是数据）
     * @alias module:model/AuthMeDataBandVisibility
     */
    constructor() { 
        
        AuthMeDataBandVisibility.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AuthMeDataBandVisibility</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AuthMeDataBandVisibility} obj Optional instance to populate.
     * @return {module:model/AuthMeDataBandVisibility} The populated <code>AuthMeDataBandVisibility</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AuthMeDataBandVisibility();

            if (data.hasOwnProperty('field_group_1_raw')) {
                obj['field_group_1_raw'] = ApiClient.convertToType(data['field_group_1_raw'], 'Boolean');
            }
            if (data.hasOwnProperty('field_group_2_status')) {
                obj['field_group_2_status'] = ApiClient.convertToType(data['field_group_2_status'], 'Boolean');
            }
            if (data.hasOwnProperty('field_group_3_gap_reason')) {
                obj['field_group_3_gap_reason'] = ApiClient.convertToType(data['field_group_3_gap_reason'], 'Boolean');
            }
            if (data.hasOwnProperty('field_group_4_derived')) {
                obj['field_group_4_derived'] = ApiClient.convertToType(data['field_group_4_derived'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>AuthMeDataBandVisibility</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>AuthMeDataBandVisibility</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} field_group_1_raw
 */
AuthMeDataBandVisibility.prototype['field_group_1_raw'] = undefined;

/**
 * @member {Boolean} field_group_2_status
 */
AuthMeDataBandVisibility.prototype['field_group_2_status'] = undefined;

/**
 * @member {Boolean} field_group_3_gap_reason
 */
AuthMeDataBandVisibility.prototype['field_group_3_gap_reason'] = undefined;

/**
 * @member {Boolean} field_group_4_derived
 */
AuthMeDataBandVisibility.prototype['field_group_4_derived'] = undefined;






export default AuthMeDataBandVisibility;

