/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BandAvailableDatesDataRetentionWindowDays from './BandAvailableDatesDataRetentionWindowDays';

/**
 * The BandAvailableDatesData model module.
 * @module model/BandAvailableDatesData
 * @version api-contract-v1.0.0
 */
class BandAvailableDatesData {
    /**
     * Constructs a new <code>BandAvailableDatesData</code>.
     * @alias module:model/BandAvailableDatesData
     */
    constructor() { 
        
        BandAvailableDatesData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BandAvailableDatesData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BandAvailableDatesData} obj Optional instance to populate.
     * @return {module:model/BandAvailableDatesData} The populated <code>BandAvailableDatesData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BandAvailableDatesData();

            if (data.hasOwnProperty('probe_id')) {
                obj['probe_id'] = ApiClient.convertToType(data['probe_id'], 'String');
            }
            if (data.hasOwnProperty('retention_window_days')) {
                obj['retention_window_days'] = BandAvailableDatesDataRetentionWindowDays.constructFromObject(data['retention_window_days']);
            }
            if (data.hasOwnProperty('pull_start_date')) {
                obj['pull_start_date'] = ApiClient.convertToType(data['pull_start_date'], 'Date');
            }
            if (data.hasOwnProperty('earliest_available')) {
                obj['earliest_available'] = ApiClient.convertToType(data['earliest_available'], 'Date');
            }
            if (data.hasOwnProperty('latest_available')) {
                obj['latest_available'] = ApiClient.convertToType(data['latest_available'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BandAvailableDatesData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BandAvailableDatesData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['probe_id'] && !(typeof data['probe_id'] === 'string' || data['probe_id'] instanceof String)) {
            throw new Error("Expected the field `probe_id` to be a primitive type in the JSON string but got " + data['probe_id']);
        }
        // validate the optional field `retention_window_days`
        if (data['retention_window_days']) { // data not null
          BandAvailableDatesDataRetentionWindowDays.validateJSON(data['retention_window_days']);
        }

        return true;
    }


}



/**
 * @member {String} probe_id
 */
BandAvailableDatesData.prototype['probe_id'] = undefined;

/**
 * @member {module:model/BandAvailableDatesDataRetentionWindowDays} retention_window_days
 */
BandAvailableDatesData.prototype['retention_window_days'] = undefined;

/**
 * 服务端计算 start = max(last_synced_date + 1, today − retention_window_days)；上界 = today（含当日）
 * @member {Date} pull_start_date
 */
BandAvailableDatesData.prototype['pull_start_date'] = undefined;

/**
 * @member {Date} earliest_available
 */
BandAvailableDatesData.prototype['earliest_available'] = undefined;

/**
 * @member {Date} latest_available
 */
BandAvailableDatesData.prototype['latest_available'] = undefined;






export default BandAvailableDatesData;

