/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BandSyncStatusData model module.
 * @module model/BandSyncStatusData
 * @version api-contract-v1.0.0
 */
class BandSyncStatusData {
    /**
     * Constructs a new <code>BandSyncStatusData</code>.
     * @alias module:model/BandSyncStatusData
     */
    constructor() { 
        
        BandSyncStatusData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BandSyncStatusData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BandSyncStatusData} obj Optional instance to populate.
     * @return {module:model/BandSyncStatusData} The populated <code>BandSyncStatusData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BandSyncStatusData();

            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('synced_date')) {
                obj['synced_date'] = ApiClient.convertToType(data['synced_date'], 'Date');
            }
            if (data.hasOwnProperty('next_action')) {
                obj['next_action'] = ApiClient.convertToType(data['next_action'], 'String');
            }
            if (data.hasOwnProperty('fail_reason_class')) {
                obj['fail_reason_class'] = ApiClient.convertToType(data['fail_reason_class'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BandSyncStatusData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BandSyncStatusData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['next_action'] && !(typeof data['next_action'] === 'string' || data['next_action'] instanceof String)) {
            throw new Error("Expected the field `next_action` to be a primitive type in the JSON string but got " + data['next_action']);
        }
        // ensure the json data is a string
        if (data['fail_reason_class'] && !(typeof data['fail_reason_class'] === 'string' || data['fail_reason_class'] instanceof String)) {
            throw new Error("Expected the field `fail_reason_class` to be a primitive type in the JSON string but got " + data['fail_reason_class']);
        }

        return true;
    }


}



/**
 * @member {module:model/BandSyncStatusData.StateEnum} state
 */
BandSyncStatusData.prototype['state'] = undefined;

/**
 * 精确到日
 * @member {Date} synced_date
 */
BandSyncStatusData.prototype['synced_date'] = undefined;

/**
 * @member {String} next_action
 */
BandSyncStatusData.prototype['next_action'] = undefined;

/**
 * 仅技术类，无未佩戴
 * @member {String} fail_reason_class
 */
BandSyncStatusData.prototype['fail_reason_class'] = undefined;





/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
BandSyncStatusData['StateEnum'] = {

    /**
     * value: "syncing"
     * @const
     */
    "syncing": "syncing",

    /**
     * value: "synced"
     * @const
     */
    "synced": "synced",

    /**
     * value: "sync_failed"
     * @const
     */
    "sync_failed": "sync_failed",

    /**
     * value: "no_data_today"
     * @const
     */
    "no_data_today": "no_data_today"
};



export default BandSyncStatusData;

