/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BandAvailableDatesRequest model module.
 * @module model/BandAvailableDatesRequest
 * @version api-contract-v1.0.0
 */
class BandAvailableDatesRequest {
    /**
     * Constructs a new <code>BandAvailableDatesRequest</code>.
     * @alias module:model/BandAvailableDatesRequest
     * @param deviceId {String} 
     * @param historyType {String} 与厂商枚举对齐（13 条逐日接口对应的 HistoryType；12 按日 + 1 游标）
     * @param validHistoryDates {Array.<Date>} getValidHistoryDates 原样返回（设备端实际存在的日期）
     * @param probedAt {Date} 
     */
    constructor(deviceId, historyType, validHistoryDates, probedAt) { 
        
        BandAvailableDatesRequest.initialize(this, deviceId, historyType, validHistoryDates, probedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, deviceId, historyType, validHistoryDates, probedAt) { 
        obj['device_id'] = deviceId;
        obj['history_type'] = historyType;
        obj['valid_history_dates'] = validHistoryDates;
        obj['probed_at'] = probedAt;
    }

    /**
     * Constructs a <code>BandAvailableDatesRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BandAvailableDatesRequest} obj Optional instance to populate.
     * @return {module:model/BandAvailableDatesRequest} The populated <code>BandAvailableDatesRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BandAvailableDatesRequest();

            if (data.hasOwnProperty('device_id')) {
                obj['device_id'] = ApiClient.convertToType(data['device_id'], 'String');
            }
            if (data.hasOwnProperty('history_type')) {
                obj['history_type'] = ApiClient.convertToType(data['history_type'], 'String');
            }
            if (data.hasOwnProperty('valid_history_dates')) {
                obj['valid_history_dates'] = ApiClient.convertToType(data['valid_history_dates'], ['Date']);
            }
            if (data.hasOwnProperty('probed_at')) {
                obj['probed_at'] = ApiClient.convertToType(data['probed_at'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BandAvailableDatesRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BandAvailableDatesRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BandAvailableDatesRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['device_id'] && !(typeof data['device_id'] === 'string' || data['device_id'] instanceof String)) {
            throw new Error("Expected the field `device_id` to be a primitive type in the JSON string but got " + data['device_id']);
        }
        // ensure the json data is a string
        if (data['history_type'] && !(typeof data['history_type'] === 'string' || data['history_type'] instanceof String)) {
            throw new Error("Expected the field `history_type` to be a primitive type in the JSON string but got " + data['history_type']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['valid_history_dates'])) {
            throw new Error("Expected the field `valid_history_dates` to be an array in the JSON data but got " + data['valid_history_dates']);
        }

        return true;
    }


}

BandAvailableDatesRequest.RequiredProperties = ["device_id", "history_type", "valid_history_dates", "probed_at"];

/**
 * @member {String} device_id
 */
BandAvailableDatesRequest.prototype['device_id'] = undefined;

/**
 * 与厂商枚举对齐（13 条逐日接口对应的 HistoryType；12 按日 + 1 游标）
 * @member {String} history_type
 */
BandAvailableDatesRequest.prototype['history_type'] = undefined;

/**
 * getValidHistoryDates 原样返回（设备端实际存在的日期）
 * @member {Array.<Date>} valid_history_dates
 */
BandAvailableDatesRequest.prototype['valid_history_dates'] = undefined;

/**
 * @member {Date} probed_at
 */
BandAvailableDatesRequest.prototype['probed_at'] = undefined;






export default BandAvailableDatesRequest;

