/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BandTelemetryRequest model module.
 * @module model/BandTelemetryRequest
 * @version api-contract-v1.0.0
 */
class BandTelemetryRequest {
    /**
     * Constructs a new <code>BandTelemetryRequest</code>.
     * @alias module:model/BandTelemetryRequest
     * @param deviceId {String} 
     * @param metric {module:model/BandTelemetryRequest.MetricEnum} 
     */
    constructor(deviceId, metric) { 
        
        BandTelemetryRequest.initialize(this, deviceId, metric);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, deviceId, metric) { 
        obj['device_id'] = deviceId;
        obj['metric'] = metric;
    }

    /**
     * Constructs a <code>BandTelemetryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BandTelemetryRequest} obj Optional instance to populate.
     * @return {module:model/BandTelemetryRequest} The populated <code>BandTelemetryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BandTelemetryRequest();

            if (data.hasOwnProperty('device_id')) {
                obj['device_id'] = ApiClient.convertToType(data['device_id'], 'String');
            }
            if (data.hasOwnProperty('metric')) {
                obj['metric'] = ApiClient.convertToType(data['metric'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('hour')) {
                obj['hour'] = ApiClient.convertToType(data['hour'], 'Number');
            }
            if (data.hasOwnProperty('minute')) {
                obj['minute'] = ApiClient.convertToType(data['minute'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], Object);
            }
            if (data.hasOwnProperty('interval')) {
                obj['interval'] = ApiClient.convertToType(data['interval'], 'Number');
            }
            if (data.hasOwnProperty('is_wear')) {
                obj['is_wear'] = ApiClient.convertToType(data['is_wear'], 'Number');
            }
            if (data.hasOwnProperty('raw_source')) {
                obj['raw_source'] = ApiClient.convertToType(data['raw_source'], 'String');
            }
            if (data.hasOwnProperty('current_sport_id')) {
                obj['current_sport_id'] = ApiClient.convertToType(data['current_sport_id'], 'String');
            }
            if (data.hasOwnProperty('sport_payload')) {
                obj['sport_payload'] = ApiClient.convertToType(data['sport_payload'], Object);
            }
            if (data.hasOwnProperty('sport_length')) {
                obj['sport_length'] = ApiClient.convertToType(data['sport_length'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BandTelemetryRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BandTelemetryRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BandTelemetryRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['device_id'] && !(typeof data['device_id'] === 'string' || data['device_id'] instanceof String)) {
            throw new Error("Expected the field `device_id` to be a primitive type in the JSON string but got " + data['device_id']);
        }
        // ensure the json data is a string
        if (data['metric'] && !(typeof data['metric'] === 'string' || data['metric'] instanceof String)) {
            throw new Error("Expected the field `metric` to be a primitive type in the JSON string but got " + data['metric']);
        }
        // ensure the json data is a string
        if (data['raw_source'] && !(typeof data['raw_source'] === 'string' || data['raw_source'] instanceof String)) {
            throw new Error("Expected the field `raw_source` to be a primitive type in the JSON string but got " + data['raw_source']);
        }
        // ensure the json data is a string
        if (data['current_sport_id'] && !(typeof data['current_sport_id'] === 'string' || data['current_sport_id'] instanceof String)) {
            throw new Error("Expected the field `current_sport_id` to be a primitive type in the JSON string but got " + data['current_sport_id']);
        }

        return true;
    }


}

BandTelemetryRequest.RequiredProperties = ["device_id", "metric"];

/**
 * @member {String} device_id
 */
BandTelemetryRequest.prototype['device_id'] = undefined;

/**
 * @member {module:model/BandTelemetryRequest.MetricEnum} metric
 */
BandTelemetryRequest.prototype['metric'] = undefined;

/**
 * 业务日（设备本地时区）
 * @member {Date} date
 */
BandTelemetryRequest.prototype['date'] = undefined;

/**
 * 日聚合型退化为 NULL
 * @member {Number} hour
 */
BandTelemetryRequest.prototype['hour'] = undefined;

/**
 * @member {Number} minute
 */
BandTelemetryRequest.prototype['minute'] = undefined;

/**
 * 按 metric 的 Schema
 * @member {Object} value
 */
BandTelemetryRequest.prototype['value'] = undefined;

/**
 * 采样间隔
 * @member {Number} interval
 */
BandTelemetryRequest.prototype['interval'] = undefined;

/**
 * getHealthDetail.isWear；1=佩戴 / 0=脱腕 / (-1,255)=技术性缺失（服务端强制覆写、不判行为性）
 * @member {Number} is_wear
 */
BandTelemetryRequest.prototype['is_wear'] = undefined;

/**
 * @member {String} raw_source
 */
BandTelemetryRequest.prototype['raw_source'] = undefined;

/**
 * 游标型 sport 分支
 * @member {String} current_sport_id
 */
BandTelemetryRequest.prototype['current_sport_id'] = undefined;

/**
 * @member {Object} sport_payload
 */
BandTelemetryRequest.prototype['sport_payload'] = undefined;

/**
 * 循环判据（sportLength > 1）
 * @member {Number} sport_length
 */
BandTelemetryRequest.prototype['sport_length'] = undefined;





/**
 * Allowed values for the <code>metric</code> property.
 * @enum {String}
 * @readonly
 */
BandTelemetryRequest['MetricEnum'] = {

    /**
     * value: "sleep"
     * @const
     */
    "sleep": "sleep",

    /**
     * value: "steps"
     * @const
     */
    "steps": "steps",

    /**
     * value: "hr"
     * @const
     */
    "hr": "hr",

    /**
     * value: "resting_hr"
     * @const
     */
    "resting_hr": "resting_hr",

    /**
     * value: "spo2"
     * @const
     */
    "spo2": "spo2",

    /**
     * value: "workout"
     * @const
     */
    "workout": "workout",

    /**
     * value: "bp"
     * @const
     */
    "bp": "bp",

    /**
     * value: "temp"
     * @const
     */
    "temp": "temp",

    /**
     * value: "pressure"
     * @const
     */
    "pressure": "pressure",

    /**
     * value: "met"
     * @const
     */
    "met": "met",

    /**
     * value: "mai"
     * @const
     */
    "mai": "mai",

    /**
     * value: "respiration"
     * @const
     */
    "respiration": "respiration",

    /**
     * value: "exercise"
     * @const
     */
    "exercise": "exercise"
};



export default BandTelemetryRequest;

