/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BandAvailableDatesDataRetentionWindowDays model module.
 * @module model/BandAvailableDatesDataRetentionWindowDays
 * @version api-contract-v1.0.0
 */
class BandAvailableDatesDataRetentionWindowDays {
    /**
     * Constructs a new <code>BandAvailableDatesDataRetentionWindowDays</code>.
     * 🛑 运行时探测值（&#x3D; 探测到的可用日期跨度）；未探测到 → 返回 TBD，不得回落为硬编码值
     * @alias module:model/BandAvailableDatesDataRetentionWindowDays
     * @param {(module:model/Number|module:model/String)} instance The actual instance to initialize BandAvailableDatesDataRetentionWindowDays.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            // validate integer
            if (!(typeof instance === 'number' && instance % 1 === 0)) {
                throw new Error("Invalid value. Must be integer. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into Number
            errorMessages.push("Failed to construct Number: " + err)
        }

        try {
            // validate string
            if (!(typeof instance === 'string')) {
                throw new Error("Invalid value. Must be string. Input: " + JSON.stringify(instance));
            }
            this.actualInstance = instance;
            match++;
        } catch(err) {
            // json data failed to deserialize into String
            errorMessages.push("Failed to construct String: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `BandAvailableDatesDataRetentionWindowDays` with oneOf schemas Number, String. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `BandAvailableDatesDataRetentionWindowDays` with oneOf schemas Number, String. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>BandAvailableDatesDataRetentionWindowDays</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BandAvailableDatesDataRetentionWindowDays} obj Optional instance to populate.
     * @return {module:model/BandAvailableDatesDataRetentionWindowDays} The populated <code>BandAvailableDatesDataRetentionWindowDays</code> instance.
     */
    static constructFromObject(data, obj) {
        return new BandAvailableDatesDataRetentionWindowDays(data);
    }

    /**
     * Gets the actual instance, which can be <code>Number</code>, <code>String</code>.
     * @return {(module:model/Number|module:model/String)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>Number</code>, <code>String</code>.
     * @param {(module:model/Number|module:model/String)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = BandAvailableDatesDataRetentionWindowDays.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of BandAvailableDatesDataRetentionWindowDays from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/BandAvailableDatesDataRetentionWindowDays} An instance of BandAvailableDatesDataRetentionWindowDays.
     */
    static fromJSON = function(json_string){
        return BandAvailableDatesDataRetentionWindowDays.constructFromObject(JSON.parse(json_string));
    }
}


BandAvailableDatesDataRetentionWindowDays.OneOf = ["Number", "String"];

export default BandAvailableDatesDataRetentionWindowDays;

