/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BandTelemetryData model module.
 * @module model/BandTelemetryData
 * @version api-contract-v1.0.0
 */
class BandTelemetryData {
    /**
     * Constructs a new <code>BandTelemetryData</code>.
     * @alias module:model/BandTelemetryData
     */
    constructor() { 
        
        BandTelemetryData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BandTelemetryData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BandTelemetryData} obj Optional instance to populate.
     * @return {module:model/BandTelemetryData} The populated <code>BandTelemetryData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BandTelemetryData();

            if (data.hasOwnProperty('data_source')) {
                obj['data_source'] = ApiClient.convertToType(data['data_source'], 'String');
            }
            if (data.hasOwnProperty('collected_days')) {
                obj['collected_days'] = ApiClient.convertToType(data['collected_days'], 'Number');
            }
            if (data.hasOwnProperty('synced_date')) {
                obj['synced_date'] = ApiClient.convertToType(data['synced_date'], 'Date');
            }
            if (data.hasOwnProperty('metrics')) {
                obj['metrics'] = ApiClient.convertToType(data['metrics'], [Object]);
            }
            if (data.hasOwnProperty('gap_reason')) {
                obj['gap_reason'] = ApiClient.convertToType(data['gap_reason'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BandTelemetryData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BandTelemetryData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['data_source'] && !(typeof data['data_source'] === 'string' || data['data_source'] instanceof String)) {
            throw new Error("Expected the field `data_source` to be a primitive type in the JSON string but got " + data['data_source']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['metrics'])) {
            throw new Error("Expected the field `metrics` to be an array in the JSON data but got " + data['metrics']);
        }
        // ensure the json data is a string
        if (data['gap_reason'] && !(typeof data['gap_reason'] === 'string' || data['gap_reason'] instanceof String)) {
            throw new Error("Expected the field `gap_reason` to be a primitive type in the JSON string but got " + data['gap_reason']);
        }

        return true;
    }


}



/**
 * 未接入时数值字段不下发，不得显示 0 / 空图表 / 示例数据
 * @member {module:model/BandTelemetryData.DataSourceEnum} data_source
 */
BandTelemetryData.prototype['data_source'] = undefined;

/**
 * 已采集天数（正向计数）
 * @member {Number} collected_days
 */
BandTelemetryData.prototype['collected_days'] = undefined;

/**
 * 客户可见同步时间精确到日（不得到分秒）
 * @member {Date} synced_date
 */
BandTelemetryData.prototype['synced_date'] = undefined;

/**
 * @member {Array.<Object>} metrics
 */
BandTelemetryData.prototype['metrics'] = undefined;

/**
 * 🔴 客户恒 403 / 不下发（硬约束，配置不得放开）
 * @member {module:model/BandTelemetryData.GapReasonEnum} gap_reason
 */
BandTelemetryData.prototype['gap_reason'] = undefined;





/**
 * Allowed values for the <code>data_source</code> property.
 * @enum {String}
 * @readonly
 */
BandTelemetryData['DataSourceEnum'] = {

    /**
     * value: "手环"
     * @const
     */
    "手环": "手环",

    /**
     * value: "未接入"
     * @const
     */
    "未接入": "未接入"
};


/**
 * Allowed values for the <code>gap_reason</code> property.
 * @enum {String}
 * @readonly
 */
BandTelemetryData['GapReasonEnum'] = {

    /**
     * value: "no_open"
     * @const
     */
    "no_open": "no_open",

    /**
     * value: "sync_failed"
     * @const
     */
    "sync_failed": "sync_failed",

    /**
     * value: "not_worn"
     * @const
     */
    "not_worn": "not_worn",

    /**
     * value: "compliant_removal"
     * @const
     */
    "compliant_removal": "compliant_removal",

    /**
     * value: "involuntary_technical"
     * @const
     */
    "involuntary_technical": "involuntary_technical",

    /**
     * value: "beyond_retention_window"
     * @const
     */
    "beyond_retention_window": "beyond_retention_window",

    /**
     * value: "unknown"
     * @const
     */
    "unknown": "unknown"
};



export default BandTelemetryData;

