/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BandSyncBatchRequest model module.
 * @module model/BandSyncBatchRequest
 * @version api-contract-v1.0.0
 */
class BandSyncBatchRequest {
    /**
     * Constructs a new <code>BandSyncBatchRequest</code>.
     * @alias module:model/BandSyncBatchRequest
     * @param deviceId {String} 客户级穿戴设备 ID（非门店调理设备）
     * @param customerId {String} 服务端从 token 校验归属
     * @param batchNo {String} 幂等键（Idempotency-Key 同值）
     * @param trigger {module:model/BandSyncBatchRequest.TriggerEnum} 
     * @param state {module:model/BandSyncBatchRequest.StateEnum} 四态；客户端可见的 client_sync_state（不含\"未佩戴\"取值）
     * @param syncedAt {Date} 精确记录；客户端展示精确到日
     */
    constructor(deviceId, customerId, batchNo, trigger, state, syncedAt) { 
        
        BandSyncBatchRequest.initialize(this, deviceId, customerId, batchNo, trigger, state, syncedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, deviceId, customerId, batchNo, trigger, state, syncedAt) { 
        obj['device_id'] = deviceId;
        obj['customer_id'] = customerId;
        obj['batch_no'] = batchNo;
        obj['trigger'] = trigger;
        obj['state'] = state;
        obj['synced_at'] = syncedAt;
    }

    /**
     * Constructs a <code>BandSyncBatchRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BandSyncBatchRequest} obj Optional instance to populate.
     * @return {module:model/BandSyncBatchRequest} The populated <code>BandSyncBatchRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BandSyncBatchRequest();

            if (data.hasOwnProperty('device_id')) {
                obj['device_id'] = ApiClient.convertToType(data['device_id'], 'String');
            }
            if (data.hasOwnProperty('customer_id')) {
                obj['customer_id'] = ApiClient.convertToType(data['customer_id'], 'String');
            }
            if (data.hasOwnProperty('batch_no')) {
                obj['batch_no'] = ApiClient.convertToType(data['batch_no'], 'String');
            }
            if (data.hasOwnProperty('trigger')) {
                obj['trigger'] = ApiClient.convertToType(data['trigger'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('synced_at')) {
                obj['synced_at'] = ApiClient.convertToType(data['synced_at'], 'Date');
            }
            if (data.hasOwnProperty('last_success_date')) {
                obj['last_success_date'] = ApiClient.convertToType(data['last_success_date'], 'Date');
            }
            if (data.hasOwnProperty('fail_reason_class')) {
                obj['fail_reason_class'] = ApiClient.convertToType(data['fail_reason_class'], 'String');
            }
            if (data.hasOwnProperty('next_action')) {
                obj['next_action'] = ApiClient.convertToType(data['next_action'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BandSyncBatchRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BandSyncBatchRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BandSyncBatchRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['device_id'] && !(typeof data['device_id'] === 'string' || data['device_id'] instanceof String)) {
            throw new Error("Expected the field `device_id` to be a primitive type in the JSON string but got " + data['device_id']);
        }
        // ensure the json data is a string
        if (data['customer_id'] && !(typeof data['customer_id'] === 'string' || data['customer_id'] instanceof String)) {
            throw new Error("Expected the field `customer_id` to be a primitive type in the JSON string but got " + data['customer_id']);
        }
        // ensure the json data is a string
        if (data['batch_no'] && !(typeof data['batch_no'] === 'string' || data['batch_no'] instanceof String)) {
            throw new Error("Expected the field `batch_no` to be a primitive type in the JSON string but got " + data['batch_no']);
        }
        // ensure the json data is a string
        if (data['trigger'] && !(typeof data['trigger'] === 'string' || data['trigger'] instanceof String)) {
            throw new Error("Expected the field `trigger` to be a primitive type in the JSON string but got " + data['trigger']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['fail_reason_class'] && !(typeof data['fail_reason_class'] === 'string' || data['fail_reason_class'] instanceof String)) {
            throw new Error("Expected the field `fail_reason_class` to be a primitive type in the JSON string but got " + data['fail_reason_class']);
        }
        // ensure the json data is a string
        if (data['next_action'] && !(typeof data['next_action'] === 'string' || data['next_action'] instanceof String)) {
            throw new Error("Expected the field `next_action` to be a primitive type in the JSON string but got " + data['next_action']);
        }

        return true;
    }


}

BandSyncBatchRequest.RequiredProperties = ["device_id", "customer_id", "batch_no", "trigger", "state", "synced_at"];

/**
 * 客户级穿戴设备 ID（非门店调理设备）
 * @member {String} device_id
 */
BandSyncBatchRequest.prototype['device_id'] = undefined;

/**
 * 服务端从 token 校验归属
 * @member {String} customer_id
 */
BandSyncBatchRequest.prototype['customer_id'] = undefined;

/**
 * 幂等键（Idempotency-Key 同值）
 * @member {String} batch_no
 */
BandSyncBatchRequest.prototype['batch_no'] = undefined;

/**
 * @member {module:model/BandSyncBatchRequest.TriggerEnum} trigger
 */
BandSyncBatchRequest.prototype['trigger'] = undefined;

/**
 * 四态；客户端可见的 client_sync_state（不含\"未佩戴\"取值）
 * @member {module:model/BandSyncBatchRequest.StateEnum} state
 */
BandSyncBatchRequest.prototype['state'] = undefined;

/**
 * 精确记录；客户端展示精确到日
 * @member {Date} synced_at
 */
BandSyncBatchRequest.prototype['synced_at'] = undefined;

/**
 * state=synced 时必填
 * @member {Date} last_success_date
 */
BandSyncBatchRequest.prototype['last_success_date'] = undefined;

/**
 * state=sync_failed 时必填；技术类，取值域内不得出现\"未佩戴\"语义
 * @member {module:model/BandSyncBatchRequest.FailReasonClassEnum} fail_reason_class
 */
BandSyncBatchRequest.prototype['fail_reason_class'] = undefined;

/**
 * state=sync_failed 时必填（可执行下一步）；不得只给一句\"同步失败\"
 * @member {module:model/BandSyncBatchRequest.NextActionEnum} next_action
 */
BandSyncBatchRequest.prototype['next_action'] = undefined;





/**
 * Allowed values for the <code>trigger</code> property.
 * @enum {String}
 * @readonly
 */
BandSyncBatchRequest['TriggerEnum'] = {

    /**
     * value: "on_show_cold"
     * @const
     */
    "on_show_cold": "on_show_cold",

    /**
     * value: "on_show_hot"
     * @const
     */
    "on_show_hot": "on_show_hot",

    /**
     * value: "checkin"
     * @const
     */
    "checkin": "checkin",

    /**
     * value: "daily_report"
     * @const
     */
    "daily_report": "daily_report",

    /**
     * value: "manual"
     * @const
     */
    "manual": "manual"
};


/**
 * Allowed values for the <code>state</code> property.
 * @enum {String}
 * @readonly
 */
BandSyncBatchRequest['StateEnum'] = {

    /**
     * value: "syncing"
     * @const
     */
    "syncing": "syncing",

    /**
     * value: "synced"
     * @const
     */
    "synced": "synced",

    /**
     * value: "sync_failed"
     * @const
     */
    "sync_failed": "sync_failed",

    /**
     * value: "no_data_today"
     * @const
     */
    "no_data_today": "no_data_today"
};


/**
 * Allowed values for the <code>fail_reason_class</code> property.
 * @enum {String}
 * @readonly
 */
BandSyncBatchRequest['FailReasonClassEnum'] = {

    /**
     * value: "bt_off"
     * @const
     */
    "bt_off": "bt_off",

    /**
     * value: "unauthorized"
     * @const
     */
    "unauthorized": "unauthorized",

    /**
     * value: "connect_timeout"
     * @const
     */
    "connect_timeout": "connect_timeout",

    /**
     * value: "device_low_battery"
     * @const
     */
    "device_low_battery": "device_low_battery",

    /**
     * value: "occupied_by_vendor_app"
     * @const
     */
    "occupied_by_vendor_app": "occupied_by_vendor_app",

    /**
     * value: "platform_suspended"
     * @const
     */
    "platform_suspended": "platform_suspended",

    /**
     * value: "probe_out_of_window"
     * @const
     */
    "probe_out_of_window": "probe_out_of_window"
};


/**
 * Allowed values for the <code>next_action</code> property.
 * @enum {String}
 * @readonly
 */
BandSyncBatchRequest['NextActionEnum'] = {

    /**
     * value: "open_bluetooth"
     * @const
     */
    "open_bluetooth": "open_bluetooth",

    /**
     * value: "grant_permission"
     * @const
     */
    "grant_permission": "grant_permission",

    /**
     * value: "retry"
     * @const
     */
    "retry": "retry",

    /**
     * value: "none"
     * @const
     */
    "none": "none"
};



export default BandSyncBatchRequest;

