/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CustomerDetailData model module.
 * @module model/CustomerDetailData
 * @version api-contract-v1.0.0
 */
class CustomerDetailData {
    /**
     * Constructs a new <code>CustomerDetailData</code>.
     * @alias module:model/CustomerDetailData
     */
    constructor() { 
        
        CustomerDetailData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>CustomerDetailData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CustomerDetailData} obj Optional instance to populate.
     * @return {module:model/CustomerDetailData} The populated <code>CustomerDetailData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CustomerDetailData();

            if (data.hasOwnProperty('customer_id')) {
                obj['customer_id'] = ApiClient.convertToType(data['customer_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], 'String');
            }
            if (data.hasOwnProperty('age')) {
                obj['age'] = ApiClient.convertToType(data['age'], 'Number');
            }
            if (data.hasOwnProperty('intake_profile')) {
                obj['intake_profile'] = ApiClient.convertToType(data['intake_profile'], Object);
            }
            if (data.hasOwnProperty('screening_result')) {
                obj['screening_result'] = ApiClient.convertToType(data['screening_result'], 'String');
            }
            if (data.hasOwnProperty('band_willingness')) {
                obj['band_willingness'] = ApiClient.convertToType(data['band_willingness'], 'String');
            }
            if (data.hasOwnProperty('owner_store_id')) {
                obj['owner_store_id'] = ApiClient.convertToType(data['owner_store_id'], 'String');
            }
            if (data.hasOwnProperty('serving_store_id')) {
                obj['serving_store_id'] = ApiClient.convertToType(data['serving_store_id'], 'String');
            }
            if (data.hasOwnProperty('effect_verdict')) {
                obj['effect_verdict'] = ApiClient.convertToType(data['effect_verdict'], 'String');
            }
            if (data.hasOwnProperty('as_value')) {
                obj['as_value'] = ApiClient.convertToType(data['as_value'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CustomerDetailData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CustomerDetailData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['customer_id'] && !(typeof data['customer_id'] === 'string' || data['customer_id'] instanceof String)) {
            throw new Error("Expected the field `customer_id` to be a primitive type in the JSON string but got " + data['customer_id']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['gender'] && !(typeof data['gender'] === 'string' || data['gender'] instanceof String)) {
            throw new Error("Expected the field `gender` to be a primitive type in the JSON string but got " + data['gender']);
        }
        // ensure the json data is a string
        if (data['screening_result'] && !(typeof data['screening_result'] === 'string' || data['screening_result'] instanceof String)) {
            throw new Error("Expected the field `screening_result` to be a primitive type in the JSON string but got " + data['screening_result']);
        }
        // ensure the json data is a string
        if (data['band_willingness'] && !(typeof data['band_willingness'] === 'string' || data['band_willingness'] instanceof String)) {
            throw new Error("Expected the field `band_willingness` to be a primitive type in the JSON string but got " + data['band_willingness']);
        }
        // ensure the json data is a string
        if (data['owner_store_id'] && !(typeof data['owner_store_id'] === 'string' || data['owner_store_id'] instanceof String)) {
            throw new Error("Expected the field `owner_store_id` to be a primitive type in the JSON string but got " + data['owner_store_id']);
        }
        // ensure the json data is a string
        if (data['serving_store_id'] && !(typeof data['serving_store_id'] === 'string' || data['serving_store_id'] instanceof String)) {
            throw new Error("Expected the field `serving_store_id` to be a primitive type in the JSON string but got " + data['serving_store_id']);
        }
        // ensure the json data is a string
        if (data['effect_verdict'] && !(typeof data['effect_verdict'] === 'string' || data['effect_verdict'] instanceof String)) {
            throw new Error("Expected the field `effect_verdict` to be a primitive type in the JSON string but got " + data['effect_verdict']);
        }

        return true;
    }


}



/**
 * @member {String} customer_id
 */
CustomerDetailData.prototype['customer_id'] = undefined;

/**
 * @member {String} name
 */
CustomerDetailData.prototype['name'] = undefined;

/**
 * @member {String} gender
 */
CustomerDetailData.prototype['gender'] = undefined;

/**
 * @member {Number} age
 */
CustomerDetailData.prototype['age'] = undefined;

/**
 * @member {Object} intake_profile
 */
CustomerDetailData.prototype['intake_profile'] = undefined;

/**
 * @member {String} screening_result
 */
CustomerDetailData.prototype['screening_result'] = undefined;

/**
 * @member {module:model/CustomerDetailData.BandWillingnessEnum} band_willingness
 */
CustomerDetailData.prototype['band_willingness'] = undefined;

/**
 * @member {String} owner_store_id
 */
CustomerDetailData.prototype['owner_store_id'] = undefined;

/**
 * @member {String} serving_store_id
 */
CustomerDetailData.prototype['serving_store_id'] = undefined;

/**
 * 派生字段；客户 token 请求 include=verdict → 403 VISIBILITY_DENIED
 * @member {String} effect_verdict
 */
CustomerDetailData.prototype['effect_verdict'] = undefined;

/**
 * 派生字段；客户恒不下发
 * @member {Number} as_value
 */
CustomerDetailData.prototype['as_value'] = undefined;





/**
 * Allowed values for the <code>band_willingness</code> property.
 * @enum {String}
 * @readonly
 */
CustomerDetailData['BandWillingnessEnum'] = {

    /**
     * value: "自愿佩戴"
     * @const
     */
    "自愿佩戴": "自愿佩戴",

    /**
     * value: "暂不佩戴"
     * @const
     */
    "暂不佩戴": "暂不佩戴"
};



export default CustomerDetailData;

