/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DailyReportRequest model module.
 * @module model/DailyReportRequest
 * @version api-contract-v1.0.0
 */
class DailyReportRequest {
    /**
     * Constructs a new <code>DailyReportRequest</code>.
     * @alias module:model/DailyReportRequest
     * @param date {Date} 补填窗口 ≤2 天（可配置）
     * @param answersJson {Object} 全点选，无开放输入
     * @param source {module:model/DailyReportRequest.SourceEnum} 代录须标 代核
     */
    constructor(date, answersJson, source) { 
        
        DailyReportRequest.initialize(this, date, answersJson, source);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, date, answersJson, source) { 
        obj['date'] = date;
        obj['answers_json'] = answersJson;
        obj['source'] = source;
    }

    /**
     * Constructs a <code>DailyReportRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DailyReportRequest} obj Optional instance to populate.
     * @return {module:model/DailyReportRequest} The populated <code>DailyReportRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DailyReportRequest();

            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('answers_json')) {
                obj['answers_json'] = ApiClient.convertToType(data['answers_json'], Object);
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DailyReportRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DailyReportRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DailyReportRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['source'] && !(typeof data['source'] === 'string' || data['source'] instanceof String)) {
            throw new Error("Expected the field `source` to be a primitive type in the JSON string but got " + data['source']);
        }

        return true;
    }


}

DailyReportRequest.RequiredProperties = ["date", "answers_json", "source"];

/**
 * 补填窗口 ≤2 天（可配置）
 * @member {Date} date
 */
DailyReportRequest.prototype['date'] = undefined;

/**
 * 全点选，无开放输入
 * @member {Object} answers_json
 */
DailyReportRequest.prototype['answers_json'] = undefined;

/**
 * 代录须标 代核
 * @member {module:model/DailyReportRequest.SourceEnum} source
 */
DailyReportRequest.prototype['source'] = undefined;





/**
 * Allowed values for the <code>source</code> property.
 * @enum {String}
 * @readonly
 */
DailyReportRequest['SourceEnum'] = {

    /**
     * value: "客户"
     * @const
     */
    "客户": "客户",

    /**
     * value: "代核"
     * @const
     */
    "代核": "代核"
};



export default DailyReportRequest;

