/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DailyReportData model module.
 * @module model/DailyReportData
 * @version api-contract-v1.0.0
 */
class DailyReportData {
    /**
     * Constructs a new <code>DailyReportData</code>.
     * @alias module:model/DailyReportData
     */
    constructor() { 
        
        DailyReportData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DailyReportData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DailyReportData} obj Optional instance to populate.
     * @return {module:model/DailyReportData} The populated <code>DailyReportData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DailyReportData();

            if (data.hasOwnProperty('report_id')) {
                obj['report_id'] = ApiClient.convertToType(data['report_id'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('weekly_count')) {
                obj['weekly_count'] = ApiClient.convertToType(data['weekly_count'], 'Number');
            }
            if (data.hasOwnProperty('last_week_compare')) {
                obj['last_week_compare'] = ApiClient.convertToType(data['last_week_compare'], Object);
            }
            if (data.hasOwnProperty('suggestion')) {
                obj['suggestion'] = ApiClient.convertToType(data['suggestion'], 'String');
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DailyReportData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DailyReportData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['report_id'] && !(typeof data['report_id'] === 'string' || data['report_id'] instanceof String)) {
            throw new Error("Expected the field `report_id` to be a primitive type in the JSON string but got " + data['report_id']);
        }
        // ensure the json data is a string
        if (data['suggestion'] && !(typeof data['suggestion'] === 'string' || data['suggestion'] instanceof String)) {
            throw new Error("Expected the field `suggestion` to be a primitive type in the JSON string but got " + data['suggestion']);
        }
        // ensure the json data is a string
        if (data['source'] && !(typeof data['source'] === 'string' || data['source'] instanceof String)) {
            throw new Error("Expected the field `source` to be a primitive type in the JSON string but got " + data['source']);
        }

        return true;
    }


}



/**
 * @member {String} report_id
 */
DailyReportData.prototype['report_id'] = undefined;

/**
 * @member {Date} date
 */
DailyReportData.prototype['date'] = undefined;

/**
 * 本周 X/7 天（正向计数）
 * @member {Number} weekly_count
 */
DailyReportData.prototype['weekly_count'] = undefined;

/**
 * @member {Object} last_week_compare
 */
DailyReportData.prototype['last_week_compare'] = undefined;

/**
 * @member {String} suggestion
 */
DailyReportData.prototype['suggestion'] = undefined;

/**
 * @member {String} source
 */
DailyReportData.prototype['source'] = undefined;






export default DailyReportData;

