/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class Dimension.
* @enum {}
* @readonly
*/
export default class Dimension {
    
        /**
         * value: "体能精力"
         * @const
         */
        "体能精力" = "体能精力";

    
        /**
         * value: "面部气色肤质"
         * @const
         */
        "面部气色肤质" = "面部气色肤质";

    
        /**
         * value: "肩颈腰背筋骨"
         * @const
         */
        "肩颈腰背筋骨" = "肩颈腰背筋骨";

    
        /**
         * value: "睡眠质量"
         * @const
         */
        "睡眠质量" = "睡眠质量";

    
        /**
         * value: "记忆专注"
         * @const
         */
        "记忆专注" = "记忆专注";

    
        /**
         * value: "代谢体态消化"
         * @const
         */
        "代谢体态消化" = "代谢体态消化";

    
        /**
         * value: "情绪抗压与抵抗力"
         * @const
         */
        "情绪抗压与抵抗力" = "情绪抗压与抵抗力";

    

    /**
    * Returns a <code>Dimension</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/Dimension} The enum <code>Dimension</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

