/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LoginData model module.
 * @module model/LoginData
 * @version api-contract-v1.0.0
 */
class LoginData {
    /**
     * Constructs a new <code>LoginData</code>.
     * @alias module:model/LoginData
     */
    constructor() { 
        
        LoginData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LoginData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LoginData} obj Optional instance to populate.
     * @return {module:model/LoginData} The populated <code>LoginData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LoginData();

            if (data.hasOwnProperty('token')) {
                obj['token'] = ApiClient.convertToType(data['token'], 'String');
            }
            if (data.hasOwnProperty('expires_in')) {
                obj['expires_in'] = ApiClient.convertToType(data['expires_in'], 'Number');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('client_end')) {
                obj['client_end'] = ApiClient.convertToType(data['client_end'], 'String');
            }
            if (data.hasOwnProperty('tenant_id')) {
                obj['tenant_id'] = ApiClient.convertToType(data['tenant_id'], 'String');
            }
            if (data.hasOwnProperty('staff_id')) {
                obj['staff_id'] = ApiClient.convertToType(data['staff_id'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>LoginData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>LoginData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['token'] && !(typeof data['token'] === 'string' || data['token'] instanceof String)) {
            throw new Error("Expected the field `token` to be a primitive type in the JSON string but got " + data['token']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['client_end'] && !(typeof data['client_end'] === 'string' || data['client_end'] instanceof String)) {
            throw new Error("Expected the field `client_end` to be a primitive type in the JSON string but got " + data['client_end']);
        }
        // ensure the json data is a string
        if (data['tenant_id'] && !(typeof data['tenant_id'] === 'string' || data['tenant_id'] instanceof String)) {
            throw new Error("Expected the field `tenant_id` to be a primitive type in the JSON string but got " + data['tenant_id']);
        }
        // ensure the json data is a string
        if (data['staff_id'] && !(typeof data['staff_id'] === 'string' || data['staff_id'] instanceof String)) {
            throw new Error("Expected the field `staff_id` to be a primitive type in the JSON string but got " + data['staff_id']);
        }

        return true;
    }


}



/**
 * @member {String} token
 */
LoginData.prototype['token'] = undefined;

/**
 * @member {Number} expires_in
 */
LoginData.prototype['expires_in'] = undefined;

/**
 * 客户=client / 调理师=therapist / 经络师=meridian / 门店负责人=manager / 区域督导=area / 总部运营=hq
 * @member {module:model/LoginData.RoleEnum} role
 */
LoginData.prototype['role'] = undefined;

/**
 * @member {module:model/LoginData.ClientEndEnum} client_end
 */
LoginData.prototype['client_end'] = undefined;

/**
 * @member {String} tenant_id
 */
LoginData.prototype['tenant_id'] = undefined;

/**
 * 客户无 staff_id（差异项）
 * @member {String} staff_id
 */
LoginData.prototype['staff_id'] = undefined;





/**
 * Allowed values for the <code>role</code> property.
 * @enum {String}
 * @readonly
 */
LoginData['RoleEnum'] = {

    /**
     * value: "client"
     * @const
     */
    "client": "client",

    /**
     * value: "therapist"
     * @const
     */
    "therapist": "therapist",

    /**
     * value: "meridian"
     * @const
     */
    "meridian": "meridian",

    /**
     * value: "manager"
     * @const
     */
    "manager": "manager",

    /**
     * value: "area"
     * @const
     */
    "area": "area",

    /**
     * value: "hq"
     * @const
     */
    "hq": "hq"
};


/**
 * Allowed values for the <code>client_end</code> property.
 * @enum {String}
 * @readonly
 */
LoginData['ClientEndEnum'] = {

    /**
     * value: "mp"
     * @const
     */
    "mp": "mp",

    /**
     * value: "app"
     * @const
     */
    "app": "app",

    /**
     * value: "web"
     * @const
     */
    "web": "web"
};



export default LoginData;

