/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AuthLogin200Response from '../model/AuthLogin200Response';
import AuthLoginRequest from '../model/AuthLoginRequest';
import AuthMe200Response from '../model/AuthMe200Response';
import ResultEnvelope from '../model/ResultEnvelope';

/**
* A service.
* @module api/AApi
* @version api-contract-v1.0.0
*/
export default class AApi {

    /**
    * Constructs a new AApi. 
    * @alias module:api/AApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * A1 登录，签发 token
     * @param {module:model/AuthLoginRequest} authLoginRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AuthLogin200Response} and HTTP response
     */
    authLoginWithHttpInfo(authLoginRequest) {
      let postBody = authLoginRequest;
      // verify the required parameter 'authLoginRequest' is set
      if (authLoginRequest === undefined || authLoginRequest === null) {
        throw new Error("Missing the required parameter 'authLoginRequest' when calling authLogin");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = AuthLogin200Response;
      return this.apiClient.callApi(
        '/auth/login', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * A1 登录，签发 token
     * @param {module:model/AuthLoginRequest} authLoginRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AuthLogin200Response}
     */
    authLogin(authLoginRequest) {
      return this.authLoginWithHttpInfo(authLoginRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * A2 当前身份 + 角色 + 可见性档位解算结果（可见性档位唯一权威下发点）
     * ⚠️ 本接口只下发「档位布尔值」，不下发任何业务字段 —— 它是声明，不是数据。 三端 UI 依此声明决定渲染分支，但字段仍由服务端裁剪（X-1：声明 ≠ 授权，二者须一致）。 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/AuthMe200Response} and HTTP response
     */
    authMeWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = AuthMe200Response;
      return this.apiClient.callApi(
        '/auth/me', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * A2 当前身份 + 角色 + 可见性档位解算结果（可见性档位唯一权威下发点）
     * ⚠️ 本接口只下发「档位布尔值」，不下发任何业务字段 —— 它是声明，不是数据。 三端 UI 依此声明决定渲染分支，但字段仍由服务端裁剪（X-1：声明 ≠ 授权，二者须一致）。 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/AuthMe200Response}
     */
    authMe() {
      return this.authMeWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
