/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GetCustomer200Response from '../model/GetCustomer200Response';
import ResultEnvelope from '../model/ResultEnvelope';

/**
* B service.
* @module api/BApi
* @version api-contract-v1.0.0
*/
export default class BApi {

    /**
    * Constructs a new BApi. 
    * @alias module:api/BApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * B4 客户详情（可见性裁剪重点接口）
     * 🔴 客户 token 请求含派生字段的 query（如 ?include=verdict）→ 403 VISIBILITY_DENIED， data.denied_fields 回显被拒字段名。 
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @param {Object} opts Optional parameters
     * @param {String} [include] 追加字段（如 verdict）；命中客户不可见字段组时 403 VISIBILITY_DENIED
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetCustomer200Response} and HTTP response
     */
    getCustomerWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getCustomer");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'include': opts['include']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetCustomer200Response;
      return this.apiClient.callApi(
        '/customers/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * B4 客户详情（可见性裁剪重点接口）
     * 🔴 客户 token 请求含派生字段的 query（如 ?include=verdict）→ 403 VISIBILITY_DENIED， data.denied_fields 回显被拒字段名。 
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @param {Object} opts Optional parameters
     * @param {String} opts.include 追加字段（如 verdict）；命中客户不可见字段组时 403 VISIBILITY_DENIED
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetCustomer200Response}
     */
    getCustomer(id, opts) {
      return this.getCustomerWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * B5 建档扩展档案
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ResultEnvelope} and HTTP response
     */
    getIntakeProfileWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getIntakeProfile");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ResultEnvelope;
      return this.apiClient.callApi(
        '/customers/{id}/intake-profile', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * B5 建档扩展档案
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ResultEnvelope}
     */
    getIntakeProfile(id) {
      return this.getIntakeProfileWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
