/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import AgeGroup from '../model/AgeGroup';
import Dimension from '../model/Dimension';
import ResultEnvelope from '../model/ResultEnvelope';

/**
* C service.
* @module api/CApi
* @version api-contract-v1.0.0
*/
export default class CApi {

    /**
    * Constructs a new CApi. 
    * @alias module:api/CApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * C3 评估详情
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @param {String} assessmentId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ResultEnvelope} and HTTP response
     */
    getAssessmentWithHttpInfo(id, assessmentId) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getAssessment");
      }
      // verify the required parameter 'assessmentId' is set
      if (assessmentId === undefined || assessmentId === null) {
        throw new Error("Missing the required parameter 'assessmentId' when calling getAssessment");
      }

      let pathParams = {
        'id': id,
        'assessment_id': assessmentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ResultEnvelope;
      return this.apiClient.callApi(
        '/customers/{id}/assessments/{assessment_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * C3 评估详情
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @param {String} assessmentId 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ResultEnvelope}
     */
    getAssessment(id, assessmentId) {
      return this.getAssessmentWithHttpInfo(id, assessmentId)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * C1 题库拉取（按分龄组 + 维度）
     * @param {module:model/AgeGroup} ageGroup 
     * @param {Object} opts Optional parameters
     * @param {module:model/Dimension} [dimension] 
     * @param {String} [version] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ResultEnvelope} and HTTP response
     */
    listScaleItemBanksWithHttpInfo(ageGroup, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'ageGroup' is set
      if (ageGroup === undefined || ageGroup === null) {
        throw new Error("Missing the required parameter 'ageGroup' when calling listScaleItemBanks");
      }

      let pathParams = {
      };
      let queryParams = {
        'age_group': ageGroup,
        'dimension': opts['dimension'],
        'version': opts['version']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ResultEnvelope;
      return this.apiClient.callApi(
        '/scale-item-banks', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * C1 题库拉取（按分龄组 + 维度）
     * @param {module:model/AgeGroup} ageGroup 
     * @param {Object} opts Optional parameters
     * @param {module:model/Dimension} opts.dimension 
     * @param {String} opts.version 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ResultEnvelope}
     */
    listScaleItemBanks(ageGroup, opts) {
      return this.listScaleItemBanksWithHttpInfo(ageGroup, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
