/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import DailyReportRequest from '../model/DailyReportRequest';
import ResultEnvelope from '../model/ResultEnvelope';
import SubmitDailyReport200Response from '../model/SubmitDailyReport200Response';

/**
* D service.
* @module api/DApi
* @version api-contract-v1.0.0
*/
export default class DApi {

    /**
    * Constructs a new DApi. 
    * @alias module:api/DApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * D5-b 方案查阅
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ResultEnvelope} and HTTP response
     */
    getPlanWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getPlan");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ResultEnvelope;
      return this.apiClient.callApi(
        '/plans/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * D5-b 方案查阅
     * @param {String} id 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ResultEnvelope}
     */
    getPlan(id) {
      return this.getPlanWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * D4 填报记录
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ResultEnvelope} and HTTP response
     */
    listDailyReportsWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling listDailyReports");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ResultEnvelope;
      return this.apiClient.callApi(
        '/customers/{id}/daily-reports', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * D4 填报记录
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ResultEnvelope}
     */
    listDailyReports(id) {
      return this.listDailyReportsWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * D2 服务记录（客户维度全局账本）
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @param {Object} opts Optional parameters
     * @param {Number} [page] 
     * @param {Number} [pageSize] 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ResultEnvelope} and HTTP response
     */
    listVisitsWithHttpInfo(id, opts) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling listVisits");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
        'page': opts['page'],
        'page_size': opts['pageSize']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ResultEnvelope;
      return this.apiClient.callApi(
        '/customers/{id}/visits', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * D2 服务记录（客户维度全局账本）
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @param {Object} opts Optional parameters
     * @param {Number} opts.page 
     * @param {Number} opts.pageSize 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ResultEnvelope}
     */
    listVisits(id, opts) {
      return this.listVisitsWithHttpInfo(id, opts)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * D3 每日填报提交
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @param {module:model/DailyReportRequest} dailyReportRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/SubmitDailyReport200Response} and HTTP response
     */
    submitDailyReportWithHttpInfo(id, dailyReportRequest) {
      let postBody = dailyReportRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling submitDailyReport");
      }
      // verify the required parameter 'dailyReportRequest' is set
      if (dailyReportRequest === undefined || dailyReportRequest === null) {
        throw new Error("Missing the required parameter 'dailyReportRequest' when calling submitDailyReport");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = SubmitDailyReport200Response;
      return this.apiClient.callApi(
        '/customers/{id}/daily-reports', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * D3 每日填报提交
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @param {module:model/DailyReportRequest} dailyReportRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/SubmitDailyReport200Response}
     */
    submitDailyReport(id, dailyReportRequest) {
      return this.submitDailyReportWithHttpInfo(id, dailyReportRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
