/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import BandAvailableDatesRequest from '../model/BandAvailableDatesRequest';
import BandSyncBatchRequest from '../model/BandSyncBatchRequest';
import BandTelemetryRequest from '../model/BandTelemetryRequest';
import GetBandSyncStatus200Response from '../model/GetBandSyncStatus200Response';
import GetBandTelemetry200Response from '../model/GetBandTelemetry200Response';
import ReportBandAvailableDates200Response from '../model/ReportBandAvailableDates200Response';
import ResultEnvelope from '../model/ResultEnvelope';

/**
* E service.
* @module api/EApi
* @version api-contract-v1.0.0
*/
export default class EApi {

    /**
    * Constructs a new EApi. 
    * @alias module:api/EApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * E6 客户端同步状态卡（四态）
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetBandSyncStatus200Response} and HTTP response
     */
    getBandSyncStatusWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getBandSyncStatus");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetBandSyncStatus200Response;
      return this.apiClient.callApi(
        '/customers/{id}/band/sync-status', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * E6 客户端同步状态卡（四态）
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetBandSyncStatus200Response}
     */
    getBandSyncStatus(id) {
      return this.getBandSyncStatusWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * E3 手环原始数据 + 采集状态（四端按档裁剪）
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/GetBandTelemetry200Response} and HTTP response
     */
    getBandTelemetryWithHttpInfo(id) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling getBandTelemetry");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GetBandTelemetry200Response;
      return this.apiClient.callApi(
        '/customers/{id}/band/telemetry', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * E3 手环原始数据 + 采集状态（四端按档裁剪）
     * @param {String} id 客户 ID（服务端从 token 校验租户归属）
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/GetBandTelemetry200Response}
     */
    getBandTelemetry(id) {
      return this.getBandTelemetryWithHttpInfo(id)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * E5 设备可用日期探测结果上报（N 运行时探测 · 禁硬编码）
     * 🛑 N 取运行时探测值，禁止硬编码：   · 服务端不得内置 N = 7 / N = 14 等任何常量；   · retention_window_days 一律取自本接口 valid_history_dates 的计算结果；   · 未探测到 → 返回 TBD，UI 与文案不得给出具体天数，不得按\"数据齐全\"预设布局。 服务端计算：pull_start_date = max(last_synced_date + 1, today − retention_window_days)， 上界 = today（含当日）。 
     * @param {module:model/BandAvailableDatesRequest} bandAvailableDatesRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ReportBandAvailableDates200Response} and HTTP response
     */
    reportBandAvailableDatesWithHttpInfo(bandAvailableDatesRequest) {
      let postBody = bandAvailableDatesRequest;
      // verify the required parameter 'bandAvailableDatesRequest' is set
      if (bandAvailableDatesRequest === undefined || bandAvailableDatesRequest === null) {
        throw new Error("Missing the required parameter 'bandAvailableDatesRequest' when calling reportBandAvailableDates");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ReportBandAvailableDates200Response;
      return this.apiClient.callApi(
        '/band/available-dates', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * E5 设备可用日期探测结果上报（N 运行时探测 · 禁硬编码）
     * 🛑 N 取运行时探测值，禁止硬编码：   · 服务端不得内置 N = 7 / N = 14 等任何常量；   · retention_window_days 一律取自本接口 valid_history_dates 的计算结果；   · 未探测到 → 返回 TBD，UI 与文案不得给出具体天数，不得按\"数据齐全\"预设布局。 服务端计算：pull_start_date = max(last_synced_date + 1, today − retention_window_days)， 上界 = today（含当日）。 
     * @param {module:model/BandAvailableDatesRequest} bandAvailableDatesRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ReportBandAvailableDates200Response}
     */
    reportBandAvailableDates(bandAvailableDatesRequest) {
      return this.reportBandAvailableDatesWithHttpInfo(bandAvailableDatesRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * E1 客户端上报同步批次（四态）
     * @param {module:model/BandSyncBatchRequest} bandSyncBatchRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ResultEnvelope} and HTTP response
     */
    reportBandSyncBatchWithHttpInfo(bandSyncBatchRequest) {
      let postBody = bandSyncBatchRequest;
      // verify the required parameter 'bandSyncBatchRequest' is set
      if (bandSyncBatchRequest === undefined || bandSyncBatchRequest === null) {
        throw new Error("Missing the required parameter 'bandSyncBatchRequest' when calling reportBandSyncBatch");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ResultEnvelope;
      return this.apiClient.callApi(
        '/band/sync-batches', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * E1 客户端上报同步批次（四态）
     * @param {module:model/BandSyncBatchRequest} bandSyncBatchRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ResultEnvelope}
     */
    reportBandSyncBatch(bandSyncBatchRequest) {
      return this.reportBandSyncBatchWithHttpInfo(bandSyncBatchRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * E2 客户端上行逐日采集数据（幂等 upsert · 双分支）
     * 幂等键【双分支】（契约 §4.3）：   · 按日型 × 12 → (device_id, metric, date, hour, minute)，日聚合接口退化为 (device_id, metric, date)   · 游标型 × 1  → (device_id, 'sport', current_sport_id) 🔴 运动数据不得复用按日型幂等键。 
     * @param {module:model/BandTelemetryRequest} bandTelemetryRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/ResultEnvelope} and HTTP response
     */
    upsertBandTelemetryWithHttpInfo(bandTelemetryRequest) {
      let postBody = bandTelemetryRequest;
      // verify the required parameter 'bandTelemetryRequest' is set
      if (bandTelemetryRequest === undefined || bandTelemetryRequest === null) {
        throw new Error("Missing the required parameter 'bandTelemetryRequest' when calling upsertBandTelemetry");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = ResultEnvelope;
      return this.apiClient.callApi(
        '/band/telemetry', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * E2 客户端上行逐日采集数据（幂等 upsert · 双分支）
     * 幂等键【双分支】（契约 §4.3）：   · 按日型 × 12 → (device_id, metric, date, hour, minute)，日聚合接口退化为 (device_id, metric, date)   · 游标型 × 1  → (device_id, 'sport', current_sport_id) 🔴 运动数据不得复用按日型幂等键。 
     * @param {module:model/BandTelemetryRequest} bandTelemetryRequest 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/ResultEnvelope}
     */
    upsertBandTelemetry(bandTelemetryRequest) {
      return this.upsertBandTelemetryWithHttpInfo(bandTelemetryRequest)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
