/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AuthLogin200Response,
  AuthLoginRequest,
  AuthMe200Response,
  ListStores200Response,
  ResultEnvelope,
} from '../models/index';

export interface AuthLoginOperationRequest {
    authLoginRequest: AuthLoginRequest;
}

export interface ListStoresRequest {
    page?: number;
    pageSize?: number;
}

/**
 * 
 */
export class AApi extends runtime.BaseAPI {

    /**
     * A1 登录，签发 token
     */
    async authLoginRaw(requestParameters: AuthLoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthLogin200Response>> {
        if (requestParameters['authLoginRequest'] == null) {
            throw new runtime.RequiredError(
                'authLoginRequest',
                'Required parameter "authLoginRequest" was null or undefined when calling authLogin().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/auth/login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['authLoginRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * A1 登录，签发 token
     */
    async authLogin(requestParameters: AuthLoginOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthLogin200Response> {
        const response = await this.authLoginRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * ⚠️ 本接口只下发「档位布尔值」，不下发任何业务字段 —— 它是声明，不是数据。 三端 UI 依此声明决定渲染分支，但字段仍由服务端裁剪（X-1：声明 ≠ 授权，二者须一致）。 
     * A2 当前身份 + 角色 + 可见性档位解算结果（可见性档位唯一权威下发点）
     */
    async authMeRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthMe200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/auth/me`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * ⚠️ 本接口只下发「档位布尔值」，不下发任何业务字段 —— 它是声明，不是数据。 三端 UI 依此声明决定渲染分支，但字段仍由服务端裁剪（X-1：声明 ≠ 授权，二者须一致）。 
     * A2 当前身份 + 角色 + 可见性档位解算结果（可见性档位唯一权威下发点）
     */
    async authMe(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthMe200Response> {
        const response = await this.authMeRaw(initOverrides);
        return await response.value();
    }

    /**
     * A3 门店列表（按行级 scope 过滤）
     */
    async listStoresRaw(requestParameters: ListStoresRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListStores200Response>> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/stores`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * A3 门店列表（按行级 scope 过滤）
     */
    async listStores(requestParameters: ListStoresRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListStores200Response> {
        const response = await this.listStoresRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
