/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateCustomer200Response,
  CreateScreeningRecord200Response,
  CustomerCreateRequest,
  GetCustomer200Response,
  ResultEnvelope,
  ScreeningCreateRequest,
} from '../models/index';

export interface CreateCustomerRequest {
    customerCreateRequest: CustomerCreateRequest;
}

export interface CreateScreeningRecordRequest {
    screeningCreateRequest: ScreeningCreateRequest;
}

export interface GetCustomerRequest {
    id: string;
    include?: string;
}

export interface GetIntakeProfileRequest {
    id: string;
}

export interface PatchIntakeProfileRequest {
    id: string;
}

export interface SignConsentRequest {
    id: string;
}

/**
 * 
 */
export class BApi extends runtime.BaseAPI {

    /**
     * 需 screening_result=通过。phone 为租户内唯一（跨店识别键）。
     * B2 建档（POST /archive 语义）
     */
    async createCustomerRaw(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateCustomer200Response>> {
        if (requestParameters['customerCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'customerCreateRequest',
                'Required parameter "customerCreateRequest" was null or undefined when calling createCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customers`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['customerCreateRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 需 screening_result=通过。phone 为租户内唯一（跨店识别键）。
     * B2 建档（POST /archive 语义）
     */
    async createCustomer(requestParameters: CreateCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateCustomer200Response> {
        const response = await this.createCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 命中禁忌（result=不通过）→ 客户状态置 REJECTED，后续 B2/B3 入口 403 GATE_MISSING （missing_items=[\"screening_result\"]）。记录不可删除。 
     * B1 禁忌筛查提交（硬门禁①）
     */
    async createScreeningRecordRaw(requestParameters: CreateScreeningRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateScreeningRecord200Response>> {
        if (requestParameters['screeningCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'screeningCreateRequest',
                'Required parameter "screeningCreateRequest" was null or undefined when calling createScreeningRecord().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/screening-records`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['screeningCreateRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 命中禁忌（result=不通过）→ 客户状态置 REJECTED，后续 B2/B3 入口 403 GATE_MISSING （missing_items=[\"screening_result\"]）。记录不可删除。 
     * B1 禁忌筛查提交（硬门禁①）
     */
    async createScreeningRecord(requestParameters: CreateScreeningRecordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateScreeningRecord200Response> {
        const response = await this.createScreeningRecordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 🔴 客户 token 请求含派生字段的 query（如 ?include=verdict）→ 403 VISIBILITY_DENIED， data.denied_fields 回显被拒字段名。 
     * B4 客户详情（可见性裁剪重点接口）
     */
    async getCustomerRaw(requestParameters: GetCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetCustomer200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getCustomer().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['include'] != null) {
            queryParameters['include'] = requestParameters['include'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/customers/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 🔴 客户 token 请求含派生字段的 query（如 ?include=verdict）→ 403 VISIBILITY_DENIED， data.denied_fields 回显被拒字段名。 
     * B4 客户详情（可见性裁剪重点接口）
     */
    async getCustomer(requestParameters: GetCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetCustomer200Response> {
        const response = await this.getCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * B5 建档扩展档案
     */
    async getIntakeProfileRaw(requestParameters: GetIntakeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getIntakeProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/customers/{id}/intake-profile`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * B5 建档扩展档案
     */
    async getIntakeProfile(requestParameters: GetIntakeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.getIntakeProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * B6 补充 + 修订（append-only 留痕，不可覆盖）
     */
    async patchIntakeProfileRaw(requestParameters: PatchIntakeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchIntakeProfile().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/customers/{id}/intake-profile`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * B6 补充 + 修订（append-only 留痕，不可覆盖）
     */
    async patchIntakeProfile(requestParameters: PatchIntakeProfileRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.patchIntakeProfileRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 需 PROFILED（门禁 G1：未建档不得签知情同意书）。
     * B3 签知情同意书
     */
    async signConsentRaw(requestParameters: SignConsentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling signConsent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/customers/{id}/consents`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 需 PROFILED（门禁 G1：未建档不得签知情同意书）。
     * B3 签知情同意书
     */
    async signConsent(requestParameters: SignConsentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.signConsentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
