/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AgeGroup,
  BaselineAssessmentRequest,
  CreateCycleAssessmentRequest,
  Dimension,
  ResultEnvelope,
  SubmitBaselineAssessment200Response,
} from '../models/index';

export interface GetAssessmentRequest {
    id: string;
    assessmentId: string;
}

export interface ListScaleItemBanksRequest {
    ageGroup: AgeGroup;
    dimension?: Dimension;
    version?: string;
}

export interface SubmitBaselineAssessmentRequest {
    id: string;
    baselineAssessmentRequest: BaselineAssessmentRequest;
}

export interface SubmitCycleAssessmentRequest {
    id: string;
    createCycleAssessmentRequest: CreateCycleAssessmentRequest;
}

/**
 * 
 */
export class CApi extends runtime.BaseAPI {

    /**
     * C3 评估详情
     */
    async getAssessmentRaw(requestParameters: GetAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getAssessment().'
            );
        }

        if (requestParameters['assessmentId'] == null) {
            throw new runtime.RequiredError(
                'assessmentId',
                'Required parameter "assessmentId" was null or undefined when calling getAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/customers/{id}/assessments/{assessment_id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))).replace(`{${"assessment_id"}}`, encodeURIComponent(String(requestParameters['assessmentId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * C3 评估详情
     */
    async getAssessment(requestParameters: GetAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.getAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * C1 题库拉取（按分龄组 + 维度）
     */
    async listScaleItemBanksRaw(requestParameters: ListScaleItemBanksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['ageGroup'] == null) {
            throw new runtime.RequiredError(
                'ageGroup',
                'Required parameter "ageGroup" was null or undefined when calling listScaleItemBanks().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['ageGroup'] != null) {
            queryParameters['age_group'] = requestParameters['ageGroup'];
        }

        if (requestParameters['dimension'] != null) {
            queryParameters['dimension'] = requestParameters['dimension'];
        }

        if (requestParameters['version'] != null) {
            queryParameters['version'] = requestParameters['version'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/scale-item-banks`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * C1 题库拉取（按分龄组 + 维度）
     */
    async listScaleItemBanks(requestParameters: ListScaleItemBanksRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.listScaleItemBanksRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 错误码：5001（题组量程 ≠ 0–4 / 题组非 symptom 向 / 缺分龄锁定）→ 提交阻断。 
     * C2 基线评估提交（同源题组锁定）
     */
    async submitBaselineAssessmentRaw(requestParameters: SubmitBaselineAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmitBaselineAssessment200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling submitBaselineAssessment().'
            );
        }

        if (requestParameters['baselineAssessmentRequest'] == null) {
            throw new runtime.RequiredError(
                'baselineAssessmentRequest',
                'Required parameter "baselineAssessmentRequest" was null or undefined when calling submitBaselineAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customers/{id}/assessments/baseline`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['baselineAssessmentRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 错误码：5001（题组量程 ≠ 0–4 / 题组非 symptom 向 / 缺分龄锁定）→ 提交阻断。 
     * C2 基线评估提交（同源题组锁定）
     */
    async submitBaselineAssessment(requestParameters: SubmitBaselineAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmitBaselineAssessment200Response> {
        const response = await this.submitBaselineAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 🛑 两阶段模型第一阶段的落点：本端点只落【评估侧依据】 （cycle_assessment.verdict IS NULL = 待判定），不落任何判定结论。 判定由 F1（POST /cycle-assessments/{id}/verdicts）在同一行上补全。 错误码：5001（题组量程 ≠ 0–4 / 缺分龄锁定）；4001（同一 cycle_id 重复提交）。 
     * C4 周期评估提交（每 7 次触发）
     */
    async submitCycleAssessmentRaw(requestParameters: SubmitCycleAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling submitCycleAssessment().'
            );
        }

        if (requestParameters['createCycleAssessmentRequest'] == null) {
            throw new runtime.RequiredError(
                'createCycleAssessmentRequest',
                'Required parameter "createCycleAssessmentRequest" was null or undefined when calling submitCycleAssessment().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customers/{id}/cycle-assessments`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createCycleAssessmentRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 🛑 两阶段模型第一阶段的落点：本端点只落【评估侧依据】 （cycle_assessment.verdict IS NULL = 待判定），不落任何判定结论。 判定由 F1（POST /cycle-assessments/{id}/verdicts）在同一行上补全。 错误码：5001（题组量程 ≠ 0–4 / 缺分龄锁定）；4001（同一 cycle_id 重复提交）。 
     * C4 周期评估提交（每 7 次触发）
     */
    async submitCycleAssessment(requestParameters: SubmitCycleAssessmentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.submitCycleAssessmentRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
