/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateVisit200Response,
  DailyReportRequest,
  ResultEnvelope,
  SubmitDailyReport200Response,
} from '../models/index';

export interface CreateVisitRequest {
    id: string;
}

export interface GetPlanRequest {
    id: string;
}

export interface ListDailyReportsRequest {
    id: string;
}

export interface ListVisitsRequest {
    id: string;
    page?: number;
    pageSize?: number;
}

export interface ReviewPlanRequest {
    id: string;
}

export interface SubmitDailyReportRequest {
    id: string;
    dailyReportRequest: DailyReportRequest;
}

/**
 * 
 */
export class DApi extends runtime.BaseAPI {

    /**
     * 🛑 本接口操作的是【门店级调理设备 device】（下行、可追责）， 与【客户级手环 band】是两本台账、不得合并。 
     * D6 设备参数下发（需方案已审核）
     */
    async createDeviceDispatchRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/device-dispatches`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 🛑 本接口操作的是【门店级调理设备 device】（下行、可追责）， 与【客户级手环 band】是两本台账、不得合并。 
     * D6 设备参数下发（需方案已审核）
     */
    async createDeviceDispatch(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.createDeviceDispatchRaw(initOverrides);
        return await response.value();
    }

    /**
     * D5-a 方案出具（回炉审核）
     */
    async createPlanRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plans`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * D5-a 方案出具（回炉审核）
     */
    async createPlan(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.createPlanRaw(initOverrides);
        return await response.value();
    }

    /**
     * D1 服务核销（四道闸门）
     */
    async createVisitRaw(requestParameters: CreateVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateVisit200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createVisit().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/customers/{id}/visits`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * D1 服务核销（四道闸门）
     */
    async createVisit(requestParameters: CreateVisitRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateVisit200Response> {
        const response = await this.createVisitRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * D5-b 方案查阅
     */
    async getPlanRaw(requestParameters: GetPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plans/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * D5-b 方案查阅
     */
    async getPlan(requestParameters: GetPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.getPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * D4 填报记录
     */
    async listDailyReportsRaw(requestParameters: ListDailyReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listDailyReports().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/customers/{id}/daily-reports`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * D4 填报记录
     */
    async listDailyReports(requestParameters: ListDailyReportsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.listDailyReportsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * D2 服务记录（客户维度全局账本）
     */
    async listVisitsRaw(requestParameters: ListVisitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listVisits().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['pageSize'] != null) {
            queryParameters['page_size'] = requestParameters['pageSize'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/customers/{id}/visits`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * D2 服务记录（客户维度全局账本）
     */
    async listVisits(requestParameters: ListVisitsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.listVisitsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * D5-c 方案审核（退回必填 reason）
     */
    async reviewPlanRaw(requestParameters: ReviewPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling reviewPlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/plans/{id}/reviews`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * D5-c 方案审核（退回必填 reason）
     */
    async reviewPlan(requestParameters: ReviewPlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.reviewPlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * D3 每日填报提交
     */
    async submitDailyReportRaw(requestParameters: SubmitDailyReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SubmitDailyReport200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling submitDailyReport().'
            );
        }

        if (requestParameters['dailyReportRequest'] == null) {
            throw new runtime.RequiredError(
                'dailyReportRequest',
                'Required parameter "dailyReportRequest" was null or undefined when calling submitDailyReport().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/customers/{id}/daily-reports`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['dailyReportRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * D3 每日填报提交
     */
    async submitDailyReport(requestParameters: SubmitDailyReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SubmitDailyReport200Response> {
        const response = await this.submitDailyReportRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
