/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetBandDerived200Response,
  GetBandTelemetry200Response,
  ResultEnvelope,
} from '../models/index';

export interface GetBandDerivedRequest {
    id: string;
}

export interface GetBandTelemetryRequest {
    id: string;
}

/**
 * 
 */
export class EApi extends runtime.BaseAPI {

    /**
     * 🔴 客户 token 调本接口 → 403 VISIBILITY_DENIED，data.denied_fields 回显被拒字段名。 A3 applicable=False（无有效同步数据）时不返回 a3_value —— 避免\"0 值\"被误读为\"戴了 0 天\"。 
     * E4 派生结果（A3 / AS / effect_verdict / 退款资格）—— 仅 staff
     */
    async getBandDerivedRaw(requestParameters: GetBandDerivedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBandDerived200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getBandDerived().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/customers/{id}/band/derived`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 🔴 客户 token 调本接口 → 403 VISIBILITY_DENIED，data.denied_fields 回显被拒字段名。 A3 applicable=False（无有效同步数据）时不返回 a3_value —— 避免\"0 值\"被误读为\"戴了 0 天\"。 
     * E4 派生结果（A3 / AS / effect_verdict / 退款资格）—— 仅 staff
     */
    async getBandDerived(requestParameters: GetBandDerivedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBandDerived200Response> {
        const response = await this.getBandDerivedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * E3 手环原始数据 + 采集状态（四端按档裁剪）
     */
    async getBandTelemetryRaw(requestParameters: GetBandTelemetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetBandTelemetry200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getBandTelemetry().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/customers/{id}/band/telemetry`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * E3 手环原始数据 + 采集状态（四端按档裁剪）
     */
    async getBandTelemetry(requestParameters: GetBandTelemetryRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetBandTelemetry200Response> {
        const response = await this.getBandTelemetryRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
