/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateVerdict200Response,
  CreateVerdictRequest,
  ResultEnvelope,
} from '../models/index';

export interface CreateVerdictOperationRequest {
    id: string;
    createVerdictRequest: CreateVerdictRequest;
}

export interface ListVerdictsRequest {
    id: string;
}

/**
 * 
 */
export class FApi extends runtime.BaseAPI {

    /**
     * 🛑 A-2 起本端点的 requestBody 已捕获冻结（此前为已登记的契约缺口，客户端无法据契约生成请求）。 入参 = 判定所需的【原始事实】；判定分支（branch）由服务端按 effect_verdict × adherence_state × risk_flag 组合算出，**不得**由调用方传入 （PRD P0-12：判定出口不得混入单一 enum）。 threshold_version 是【断言位】而非取值位：可空（= 服务端填）； 非空时必须逐字等于服务端算出的内容寻址指纹，否则拒写 4001。 
     * F1 判定结论落库（含依据快照 + 阈值版本）
     */
    async createVerdictRaw(requestParameters: CreateVerdictOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateVerdict200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createVerdict().'
            );
        }

        if (requestParameters['createVerdictRequest'] == null) {
            throw new runtime.RequiredError(
                'createVerdictRequest',
                'Required parameter "createVerdictRequest" was null or undefined when calling createVerdict().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/cycle-assessments/{id}/verdicts`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['createVerdictRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 🛑 A-2 起本端点的 requestBody 已捕获冻结（此前为已登记的契约缺口，客户端无法据契约生成请求）。 入参 = 判定所需的【原始事实】；判定分支（branch）由服务端按 effect_verdict × adherence_state × risk_flag 组合算出，**不得**由调用方传入 （PRD P0-12：判定出口不得混入单一 enum）。 threshold_version 是【断言位】而非取值位：可空（= 服务端填）； 非空时必须逐字等于服务端算出的内容寻址指纹，否则拒写 4001。 
     * F1 判定结论落库（含依据快照 + 阈值版本）
     */
    async createVerdict(requestParameters: CreateVerdictOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateVerdict200Response> {
        const response = await this.createVerdictRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * 🔴 客户与调理师端一律 403 VISIBILITY_DENIED。
     * F2 判定历史
     */
    async listVerdictsRaw(requestParameters: ListVerdictsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling listVerdicts().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/customers/{id}/verdicts`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * 🔴 客户与调理师端一律 403 VISIBILITY_DENIED。
     * F2 判定历史
     */
    async listVerdicts(requestParameters: ListVerdictsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.listVerdictsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
