/* tslint:disable */
/* eslint-disable */
/**
 * 上医智养堂 · 三端接口契约（调元云）
 * 三端（客户小程序 / 调理师·经络师 APP / 管理员 Web）一次冻结的接口契约。  版本号规则（语义化，与 info.version 同值）：   - MAJOR（破坏级）：字段删除 / 改名 / 类型变更；可见性档位变更；枚举值语义变更；错误码语义变更；     涉可见性档位的 MAJOR 变更须触发「变更业务裁定」（不得按\"体验优化\"处理）。   - MINOR（兼容级）：新增可选请求字段 / 新增接口 / 新增响应字段。   - PATCH（文档级）：注释 / 示例 / 措辞修正，不动字段与语义。  🛑 措辞纪律：client_end=mp 可见字段不得含\"退款\"\"诊断\"；同步时间精确到日。 
 *
 * The version of the OpenAPI document: api-contract-v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateRefund200Response,
  CreateRefundReceipt200Response,
  RefundCreateRequest,
  ResultEnvelope,
} from '../models/index';

export interface CreateRefundRequest {
    refundCreateRequest: RefundCreateRequest;
}

export interface CreateRefundReceiptRequest {
    id: string;
}

export interface CreateRetentionRequest {
    id: string;
}

export interface GetRefundRequest {
    id: string;
}

/**
 * 
 */
export class GApi extends runtime.BaseAPI {

    /**
     * G1 代录客户退款诉求（发起方 = 经络师 / 门店负责人）
     */
    async createRefundRaw(requestParameters: CreateRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateRefund200Response>> {
        if (requestParameters['refundCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'refundCreateRequest',
                'Required parameter "refundCreateRequest" was null or undefined when calling createRefund().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/refunds`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['refundCreateRequest'],
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * G1 代录客户退款诉求（发起方 = 经络师 / 门店负责人）
     */
    async createRefund(requestParameters: CreateRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateRefund200Response> {
        const response = await this.createRefundRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * G5 回执（三态留痕）
     */
    async createRefundReceiptRaw(requestParameters: CreateRefundReceiptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateRefundReceipt200Response>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createRefundReceipt().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/refunds/{id}/receipts`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * G5 回执（三态留痕）
     */
    async createRefundReceipt(requestParameters: CreateRefundReceiptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateRefundReceipt200Response> {
        const response = await this.createRefundReceiptRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * G3 挽留记录（挽留记录必填；入口 B 不经挽留）
     */
    async createRetentionRaw(requestParameters: CreateRetentionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createRetention().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/refunds/{id}/retentions`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * G3 挽留记录（挽留记录必填；入口 B 不经挽留）
     */
    async createRetention(requestParameters: CreateRetentionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.createRetentionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * G2 退款工单详情
     */
    async getRefundRaw(requestParameters: GetRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResultEnvelope>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getRefund().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/refunds/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response);
    }

    /**
     * G2 退款工单详情
     */
    async getRefund(requestParameters: GetRefundRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResultEnvelope> {
        const response = await this.getRefundRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
